In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("virma_lipas_routes_overlap.csv")
df.head()

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,...,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio
0,302297,NaN,Virkistysreitti,rekreationsrutt,recreational route,Retkeilyreitti,vandringsrutt,hiking route,Tammimetsä,NaN,...,NaN,NaN,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[222775.35...",222885.539103,6.734340e+06,0.153
1,274,274.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Jogging track,Pitkäjärven kuntorata ja latu,NaN,...,erkki@esimerkki.fi,NaN,Kunta,Kunta / tekninen toimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[297960.33...",297824.072660,6.732238e+06,0.216
2,274,274.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Jogging track,Pitkäjärven kuntorata ja latu,NaN,...,erkki@esimerkki.fi,NaN,Kunta,Kunta / tekninen toimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[298170.66...",298234.054496,6.731609e+06,0.160
3,274,274.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Jogging track,Pitkäjärven kuntorata ja latu,NaN,...,erkki@esimerkki.fi,NaN,Kunta,Kunta / tekninen toimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[298212.37...",298229.548694,6.731974e+06,0.070
4,274,274.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Jogging track,Pitkäjärven kuntorata ja latu,NaN,...,erkki@esimerkki.fi,NaN,Kunta,Kunta / tekninen toimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[298246.71...",298097.513157,6.731861e+06,0.356

In [3]:
df.shape

(3824, 74)

In [4]:
df["gid"].nunique()

449

In [5]:
df['gid'].value_counts()

gid
305913    123
161        70
22         66
394        54
439        52
         ...
442         1
1           1
305745      1
167         1
311         1
Name: count, Length: 449, dtype: int64

In [6]:
pd.set_option('display.max_columns', None)
#pd.reset_option('display.max_rows')

df[df["gid"] == 305913]

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio
174,305913,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Jaakontie pyhiinvaellusreitti,NaN,NaN,Raisio,Turku,Varsinais-Suomi,Hämeen Härkätie on Santiago de Compostelaan jo...,NaN,NaN,NaN,242400,NaN,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,NaN,NaN,erkki@esimerkki.fi,NaN,Jakontie ystävät ry,https://jaakontienystavat.wordpress.com/,ei tietoa ylläpitoluokasta,NaN,2024/09/12,NaN,2024/09/17,NR,Pyhiinvaellus,680,023,02,T,NaN,NaN,False,notknown,False,NaN,NaN,96795,4405,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,96795,96795,Rantatie,21120,RAISIO,680,Raisio,Polun varrella 19 luontotaulua. Sopii vain jal...,6,Retkeilyreitti,Utflyktsled,Hiking route,Uikkupolku,NaN,http://www.raisio.fi/palvelut-a-o/liikunta-ja-...,NaN,NaN,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[231979.88...",231834.817988,6.714310e+06,0.001
175,305913,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Jaakontie pyhiinvaellusreitti,NaN,NaN,Raisio,Turku,Varsinais-Suomi,Hämeen Härkätie on Santiago de Compostelaan jo...,NaN,NaN,NaN,242400,NaN,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,NaN,NaN,erkki@esimerkki.fi,NaN,Jakontie ystävät ry,https://jaakontienystavat.wordpress.com/,ei tietoa ylläpitoluokasta,NaN,2024/09/12,NaN,2024/09/17,NR,Pyhiinvaellus,680,023,02,T,NaN,NaN,False,notknown,False,NaN,NaN,96795,4405,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,96795,96795,Rantatie,21120,RAISIO,680,Raisio,Polun varrella 19 luontotaulua. Sopii vain jal...,7,Retkeilyreitti,Utflyktsled,Hiking route,Uikkupolku,NaN,http://www.raisio.fi/palvelut-a-o/liikunta-ja-...,NaN,NaN,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[231679.38...",231656.130027,6.714198e+06,0.000
176,305913,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Jaakontie pyhiinvaellusreitti,NaN,NaN,Raisio,Turku,Varsinais-Suomi,Hämeen Härkätie on Santiago de Compostelaan jo...,NaN,NaN,NaN,242400,NaN,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,NaN,NaN,erkki@esimerkki.fi,NaN,Jakontie ystävät ry,https://jaakontienystavat.wordpress.com/,ei tietoa ylläpitoluokasta,NaN,2024/09/12,NaN,2024/09/17,NR,Pyhiinvaellus,680,023,02,T,NaN,NaN,False,notknown,False,NaN,NaN,96795,4405,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,96795,96795,Rantatie,21120,RAISIO,680,Raisio,Polun varrella 19 luontotaulua. Sopii vain jal...,9,Retkeilyreitti,Utflyktsled,Hiking route,Uikkupolku,NaN,http://www.raisio.fi/palvelut-a-o/liikunta-ja-...,NaN,NaN,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[232095.38...",232035.071786,6.714318e+06,0.001
177,305913,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Jaakontie pyhiinvaellusreitti,NaN,NaN,Raisio,Turku,Varsinais-Suomi,Hämeen Härkätie on Santiago de Compostelaan jo...,NaN,NaN,NaN,242400,NaN,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,NaN,NaN,erkki@esimerkki.fi,NaN,Jakontie ystävät ry,https://jaakontienystavat.wordpress.com/,ei tietoa ylläpitoluokasta,NaN,2024/09/12,NaN,2024/09/17,NR,Pyhiinvaellus,680,023,02,T,NaN,NaN,False,notknown,False,NaN,NaN,96795,4405,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,96795,96795,Rantatie,21120,RAISIO,680,Raisio,Polun varrella 19 luontotaulua. Sopii vain jal...,10,Retkeilyreitti,Utflyktsled,Hiking route,Uikkupolku,NaN,http://www.raisio.fi/palvelut-a-o/liikunta-ja-...,NaN,NaN,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[232097.38...",232399.567004,6.713818e+06,0.002
178,305913,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Jaakontie pyhiinvaellusreitti,NaN,NaN,Raisio,Turku,Varsinais-Suomi,Hämeen Härkätie on Santiago de Compostelaan jo...,NaN,NaN,NaN,242400,NaN,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,NaN,NaN,erkki@esimerkki.fi,NaN,Jakontie ystävät ry,https://jaakontienystavat.wordpress.com/,ei tietoa ylläpitoluokasta,NaN,2024/09/12,NaN,2024/09/17,NR,Pyhiinvaellus,680,023,02,T,NaN,NaN,False,notknown,False,NaN,NaN,525507,4405,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,525507,525507,Turku,20100,Turku,853,Turku,Paavonpolut on merkitty sinisillä merkeillä. M...,13,Retkeilyreitti,Utflyktsled,Hiking route,Paavonpolut,NaN,https://www.turku.fi/vapaa-aika/ulkoilualueet/...,NaN,NaN,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[238967.28...",238376.935996,6.712182e+06,0.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,305913,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Jaakontie pyhiinvaellusreitti,NaN,NaN,Raisio,Turku,Varsinais-Suomi,Hämeen Härkätie on Santiago de Compostelaan jo...,NaN,NaN,NaN,242400,NaN,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,NaN,NaN,erkki@esimerkki.fi,NaN,Jakontie ystävät ry,https://jaakontienystavat.wordpress.com/,ei tietoa ylläpitoluokasta,NaN,2024/09/12,NaN,2024/09/17,NR,Pyhiinvaellus,680,023,02,T,NaN,NaN,False,notknown,False,NaN,NaN,603149,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,603149,603149,Vanha Härkätie 111,21410,Vanhalinna,423,Lieto,NaN,4,Luontopolku,Naturstig,Nature trail,Liedon Vanhalinnan kulttuuri- ja luontopolut,NaN,http://www.reitisto.fi/liedonvanhalinna,NaN,NaN,Säätiö,Säätiö,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[245984.44...",246045.172624,6.714456e+06,0.000
293,305913,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Jaakontie pyhiinvaellusreitti,NaN,NaN,Raisio,Turku,Varsinais-Suomi,Hämeen Härkätie on Santiago de Compostelaan jo...,NaN,NaN,NaN,242400,NaN,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,NaN,NaN,erkki@esimerkki.fi,NaN,Jakontie ystävät ry,https://jaakontienystavat.wordpress.com/,ei tietoa ylläpitoluokasta,NaN,2024/09/12,NaN,2024/09/17,NR,Pyhiinvaellus,680,023,02,T,NaN,NaN,False,notknown,False,NaN,NaN,603149,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,603149,603149,Vanha Härkätie 111,21410,Vanhalinna,423,Lieto,NaN,6,Luontopolku,Naturstig,Nature trail,Liedon Vanhalinnan kulttuuri- ja luontopolut,NaN,http://www.reitisto.fi/liedonvanhalinna,NaN,NaN,Säätiö,Säätiö,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246138.39...",246106.853971,6.714204e+06,0.000
294,305913,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Jaakontie pyhiinvaellusreitti,NaN,NaN,Raisio,Turku,Varsinais-Suomi,Hämeen Härkätie on Santiago de Compostelaan jo...,NaN,NaN,NaN,242400,NaN,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,NaN,NaN,erkki@esimerkki.fi,NaN,Jakontie ystävät ry,https://jaakontienystavat.wordpress.com/,ei tietoa ylläpitoluokasta,NaN,2024/09/12,NaN,2024/09/17,NR,Pyhiinvaellus,680,023,02,T,NaN,NaN,False,notknown,False,NaN,NaN,603149,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,603149,603149,Vanha Härkätie 111,21410,Vanhalinna,423,Lieto,NaN,9,Luontopolku,Naturstig,Nature trail,Liedon Vanhalinnan kulttuuri- ja luontopolut,NaN,http://www.reitisto.fi/liedonvanhalinna,NaN,NaN,Säätiö,Säätiö,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246138.39...",246126.094599,6.714426e+06,0.000
295,305913,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Jaakontie pyhiinvaellusreitti,NaN,NaN,Raisio,Turku,Varsinais-Suomi,Hämeen Härkätie on Santiago de Compostelaan jo...,NaN,NaN,NaN,242400,NaN,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,NaN,NaN,erkki@esimerkki.fi,NaN,Jakontie ystävät ry,https://jaakontienystavat.wordpress.com/,ei tietoa ylläpitoluokasta,NaN,2024/09/12,NaN,2024/09/17,NR,Pyhiinvaellus,680,023,02,T,NaN,NaN,False,notknown,False,NaN,NaN,603149,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,603149,603149,Vanha Härkätie 111,21410,Vanhalinna,423,Lieto,NaN,8,Luontopolku,Naturstig,Nature trail,Liedon Vanhalinnan kulttuuri- ja luontopolut,NaN,http://www.reitisto.fi/liedonvanhalinna,NaN,NaN,Säätiö,Säätiö,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246297.45...",246353.657700,6.714387e+06,0.001
296,305913,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Jaakontie pyhiinvaellusreitti,NaN,NaN,Raisio,Turku,Varsinais-Suomi,Hämeen Härkätie on Santiago de Compostelaan jo...,NaN,NaN,NaN,242400,NaN,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,NaN,NaN,erkki@esimerkki.fi,NaN,Jakontie ystävät ry,https://jaakontienystavat.wordpress.com/,ei tietoa ylläpitoluokasta,NaN,2024/09/12,NaN,2024/09/17,NR,Pyhiinvaellus,680,023,02,T,NaN,NaN,False,notknown,False,NaN,NaN,603149,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,603149,603149,Vanha Härkätie 111,21410,Vanhalinna,423,Lieto,NaN,10,Luontopolku,Naturstig,Nature trail,Liedon Vanhalinnan kulttuuri- ja luontopolut,NaN,http://www.reitisto.fi/liedonvanhalinna,NaN,NaN,Säätiö,Säätiö,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[245766.36...",245928.906630,6.713990e+06,0.000

In [7]:
agg_dict = {col: 'first' for col in df.columns if col not in ['overlap_ratio']}
agg_dict['overlap_ratio'] = 'sum'

summed_df = df.groupby(['gid', 'id_2'], as_index=False).agg(agg_dict)

In [8]:
summed_df.shape

(1553, 74)

In [9]:
summed_df.loc[summed_df["name_fi"] == "Vretan latu"]

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio
1243,302490,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,NaN,NaN,92599,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,92599,92599,Länsiniementie 101,25700,Kemiö,322,Kemiönsaari,"Lenkit 1,5 km ja 2,5 km.",2,Kuntorata,Konditionsbana,Jogging track,Vretan kuntorata,Vreta motionsbana,www.ksf.sporttisaitti.com,None,None,Rekisteröity yhdistys,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260399.56...",260466.442411,6.677834e+06,1.096
1244,302490,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,NaN,NaN,528520,4402,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,528520,528520,Länsiniementie 101,25700,Kemiö,322,Kemiönsaari,"Lenkit 1,5 km ja 2,5 km.",2,Hiihtolatu,Skidspår,Ski track,Vretan Långdalenin latu,Vreta Långdalens skidspår,www.ksf.sporttisaitti.com,None,None,Rekisteröity yhdistys,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260646.78...",260500.922442,6.677761e+06,1.104
1245,302490,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,NaN,NaN,604266,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,604266,604266,Engelsbyntie 8,25700,None,322,Kemiönsaari,None,39,Pyöräilyreitti,Cykelled,Biking route,Rannikkoreitti,Kustrutten,www.rannikkoreitti.fi,None,None,Kunta,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[264609.44...",254803.828095,6.671355e+06,0.013
1246,302490,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,NaN,NaN,609981,4402,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,609981,609981,Länsiniementie 101,25710,None,322,Kemiönsaari,None,1,Hiihtolatu,Skidspår,Ski track,Långdalenin peltolatu,Långdalens åkerbana,None,None,None,Kunta,Muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260824.65...",261113.238879,6.677799e+06,0.006
1336,302522,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,NaN,NaN,92599,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,92599,92599,Länsiniementie 101,25700,Kemiö,322,Kemiönsaari,"Lenkit 1,5 km ja 2,5 km.",2,Kuntorata,Konditionsbana,Jogging track,Vretan kuntorata,Vreta motionsbana,www.ksf.sporttisaitti.com,None,None,Rekisteröity yhdistys,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260399.56...",260466.442411,6.677834e+06,1.096
1337,302522,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,NaN,NaN,528520,4402,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,528520,528520,Länsiniementie 101,25700,Kemiö,322,Kemiönsaari,"Lenkit 1,5 km ja 2,5 km.",2,Hiihtolatu,Skidspår,Ski track,Vretan Långdalenin latu,Vreta Långdalens skidspår,www.ksf.sporttisaitti.com,None,None,Rekisteröity yhdistys,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260646.78...",260500.922442,6.677761e+06,1.104
1338,302522,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,NaN,NaN,604266,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,604266,604266,Engelsbyntie 8,25700,None,322,Kemiönsaari,None,39,Pyöräilyreitti,Cykelled,Biking route,Rannikkoreitti,Kustrutten,www.rannikkoreitti.fi,None,None,Kunta,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[264609.44...",254803.828095,6.671355e+06,0.013
1339,302522,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,NaN,NaN,609981,4402,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,609981,609981,Länsiniementie 101,25710,None,322,Kemiönsaari,None,1,Hiihtolatu,Skidspår,Ski track,Långdalenin peltolatu,Långdalens åkerbana,None,None,None,Kunta,Muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260824.65...",261113.238879,6.677799e+06,0.006

In [10]:
df.loc[df["overlap_ratio"] == 1, ["name_fi", "nimi_fi"]]

,name_fi,nimi_fi
43,Salon Pahkavuoren kuntorata,Pahkavuoren kuntorata
403,Aurajoen pyhiinvaelluspolut - Helenan polku,Helenan polku
502,Paimion muurahaispolku,Muurahaispolku
706,Vänön luontopolku,Vänön luontopolku
1553,Vahdon kuntorata,Vahdon kuntorata
1833,Loimaan eteläinen kuntorata,Eteläinen kuntorata
1867,Tuorlan esteetön luontopolku,Tuorlan esteetön luontopolku
2135,Pöytyän Riihikosken urheilupuiston kuntorata,Riihikosken kuntorata
2255,Kuusiston koulupolku,Kuusiston koulupolku
2512,Höglandin lyhyempi luontopolku,Höglandin luontopolku
2645,Tikanmaan kuntorata,Tikanmaan kuntorata
2656,Merttelän pururata,Merttelän kuntorata
2660,Isohärjänmäen kuntorata,Isohärjänmäen kuntorata
2664,Urheilupuiston kuntorata: Karikon lenkki,Urheilupuiston kuntorata - Karikon lenkki
2770,Pansion kuntorata,Pansion kuntorata
2799,Suikkilan kuntorata,Suikkilan kuntorata
3218,Hovirinnan kuntorata,Hovirinnan kuntorata
3228,Tikanmaan kuntorata,Tikanmaan kuntorata
3299,Hujalan hiihtokeskuksen reitit,Hujalan kuntorata
3308,Haijaisten kuntorata,Haijaisten kuntorata
3441,Suontaan latu,Suontaan pururata
3552,Paavonpolut: Yhdysreitti: Lauste-Varissuo,Paavonpolut
3754,Paavonpolut: Rautatiesilta-Halistenkoski,Paavonpolut

In [11]:
summed_df.loc[summed_df["overlap_ratio"] >= 1, ["name_fi", "nimi_fi"]]

,name_fi,nimi_fi
1,Kuusiston koulupolku,Kuusiston koulupolku
11,tuntematon 5,Ankka-Nautela luontopolku
14,Loukinaisten kuntorata,Loukinaisten valaistu ulkoilurata
103,Pöytyän Riihikosken urheilupuiston kuntorata,Riihikosken kuntorata
124,Mynäjoen melontareitti,Mynäjoen melontareitti
...,...,...
1243,Vretan latu,Vretan kuntorata
1244,Vretan latu,Vretan Långdalenin latu
1336,Vretan latu,Vretan kuntorata
1337,Vretan latu,Vretan Långdalenin latu
1519,Aurajoen pyhiinvaelluspolut - Helenan polku,Helenan polku

In [12]:
mapping_df = pd.read_csv("mappings.csv")
mapping_df

,id,virma_class2_fi,lipas_type_name,lipas_type_code,confirmed,lipas_loi_type
0,5.0,Virkistykseen liittyvä erityiskohde,NaN,NaN,False,NaN
1,7.0,Päivälaavu tai -kota,"Laavu, kota tai kammi",301.0,False,NaN
2,12.0,Matkailureitti,NaN,NaN,False,NaN
3,13.0,Tupa,Tupa,302.0,False,NaN
4,16.0,Käyntisatama,Veneilyn palvelupaikka,203.0,False,NaN
...,...,...,...,...,...,...
64,25.0,Hätäsatama,Veneilyn palvelupaikka,203.0,False,NaN
65,74.0,Luonnonmuistomerkki tai näköalapaikka,NaN,NaN,False,viewing-platform
66,36.0,Keittokatos- / ruoanlaittopaikka,Ruoanlaitto-/tulentekopaikka,206.0,False,NaN
67,66.0,Latu,Hiihtolatu,NaN,NaN,NaN
68,NaN,Retkilatu,Hiihtolatu,NaN,NaN,NaN

In [13]:
mapping_df = mapping_df.drop(columns=['lipas_type_code', 'confirmed', 'lipas_loi_type', "id"])
mapping_df

                          virma_class2_fi               lipas_type_name
0     Virkistykseen liittyvä erityiskohde                           NaN
1                    Päivälaavu tai -kota         Laavu, kota tai kammi
2                          Matkailureitti                           NaN
3                                    Tupa                          Tupa
4                            Käyntisatama        Veneilyn palvelupaikka
..                                    ...                           ...
64                             Hätäsatama        Veneilyn palvelupaikka
65  Luonnonmuistomerkki tai näköalapaikka                           NaN
66       Keittokatos- / ruoanlaittopaikka  Ruoanlaitto-/tulentekopaikka
67                                   Latu                    Hiihtolatu
68                              Retkilatu                    Hiihtolatu

[69 rows x 2 columns]

In [14]:
mapping_dict = dict(zip(mapping_df['virma_class2_fi'], mapping_df['lipas_type_name']))
mapping_dict

{'Virkistykseen liittyvä erityiskohde': nan,
 'Päivälaavu tai -kota': 'Laavu, kota tai kammi',
 'Matkailureitti': nan,
 'Tupa': 'Tupa',
 'Käyntisatama': 'Veneilyn palvelupaikka',
 'Opastuskeskus': 'Opastuspiste',
 'Talviuimapaikka': 'Talviuintipaikka',
 'Melontareitti': 'Melontareitti',
 'Virkistysreitin lähtöpiste': 'Opastuspiste',
 'Tulipaikka': 'Ruoanlaitto-/tulentekopaikka',
 'Opaspalvelu': 'Opastuspiste',
 'Latu': 'Hiihtolatu',
 'Vierassatama': 'Veneilyn palvelupaikka',
 'Uimaranta': 'Uimaranta',
 'Retkeilyreitti': 'Retkeilyreitti',
 'Kalastuspaikka': 'Kalastuskohde (piste)',
 'Uimapaikka': 'Uimapaikka',
 'Retkilatu': 'Hiihtolatu',
 'Luonto- tai lintutorni': 'Luontotorni',
 'Ulkoilu- tai hiihtomaja': 'Ulkoilumaja/hiihtomaja',
 'Telttailupaikka': 'Telttailu ja leiriytyminen',
 'Kuntoreitti': 'Kuntorata',
 'Moottorirata': 'Moottoripyöräilyalue',
 'Muu virkistystä tukeva palvelu': nan,
 'Kulttuuripalvelu': nan,
 'Leirintä- tai caravanalue': 'Telttailu ja leiriytyminen',
 'Opastuspiste': 'Opastuspiste',
 'Retki- tai luonnonsatama': 'Veneilyn palvelupaikka',
 'Maastopyöräilyreitti': 'Maastopyöräilyreitti',
 'Palvelusatama': 'Veneilyn palvelupaikka',
 'Luontopolku': 'Luontopolku',
 'Pyöräilyreitti': 'Pyöräilyreitti',
 'Hevosreitti': 'Hevosreitti',
 'Veneenlaskupaikka': nan,
 'Yöpymislaavu tai -kota': 'Laavu, kota tai kammi',
 'Varauslaavu tai -kota': 'Laavu, kota tai kammi',
 'Majoituspalvelu': nan,
 'Yhteysaluslaituri': nan,
 'Retkeilyä palveleva parkkipaikka': nan,
 'Levähdyspaikka': nan,
 'Luonnonmuistomerkki tai näköalapaikka': nan,
 'Sauna': nan,
 'Varaussauna': nan,
 'Tilavuokraus- tai kokouspalvelu': nan,
 'Yleisö-wc tai -puucee': nan,
 'Polttopuusuoja': nan,
 'Jätepiste': nan,
 'Vesipiste': nan,
 'Lähde tai kaivo': nan,
 'Vieraslaituri': nan,
 'Leirikeskus': nan,
 'Rantautumispaikka': 'Veneilyn palvelupaikka',
 'Kulttuuriulkoilureitti': 'Kävelyreitti/ulkoilureitti',
 'Ruokapalvelu': nan,
 'Myymälä': nan,
 'Ohjelma- tai elämyspalvelu': nan,
 'Kahvila': nan,
 'Ravintola': nan,
 'Ankkuripaikka': 'Veneilyn palvelupaikka',
 'Suojasatama': 'Veneilyn palvelupaikka',
 'Hätäsatama': 'Veneilyn palvelupaikka',
 'Keittokatos- / ruoanlaittopaikka': 'Ruoanlaitto-/tulentekopaikka'}

In [15]:
summed_df.loc[
    (summed_df['overlap_ratio'] >= 1) &
    (summed_df['tyyppi_nimi_fi'] == summed_df['class2_fi'].map(mapping_dict))
]

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio
14,11,11.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Loukinaisten kuntorata,None,None,Lieto,Turun seutu,Varsinais-Suomi,"2,1 km pitkä valaistu kuntorata. Talvisin kunt...",None,None,None,2200,None,http://www.lieto.fi/,None,None,None,None,Liedon kunta,None,ei tietoa ylläpitoluokasta,None,None,None,2022/11/14,tuomohy,None,423,23,02,F,None,None,False,notknown,False,NaN,NaN,515096,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,515096,515096,Airikintie,21410,Vanhalinna,423,Lieto,Talvikaudella kävely ja ulkoilu. Ei latua.,7,Kuntorata,Konditionsbana,Jogging track,Loukinaisten valaistu ulkoilurata,None,http://www.lieto.fi/,None,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[247163.76...",247188.208809,6.713565e+06,1.059
103,20,20.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Pöytyän Riihikosken urheilupuiston kuntorata,Riihikoski i Pöytis motionsbana,Pöytyä Riihikoski fitness trail,Pöytyä,Loimaan seutu,Varsinais-Suomi,Valaistu 1 km kuntorata. Maapohjan omistaa Pöy...,Upplyst 1 km motionsbana,1 km fitness trail with public lightning.,None,1000,None,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,None,None,Pöytyän kunta,None,ei tietoa ylläpitoluokasta,None,None,None,2023/08/22,LN,None,636,25,02,F,None,None,False,notknown,False,NaN,NaN,95745,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,95745,95745,Yläneentie 14,21870,Riihikoski,636,Pöytyä,None,1,Kuntorata,Konditionsbana,Jogging track,Riihikosken kuntorata,None,None,None,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[259734.77...",259577.326500,6.739808e+06,1.000
124,23,23.0,Virkistysreitti,Rekreationsrutt,Recreational route,Melontareitti,Paddlingsrutt,Canoeing route,Mynäjoen melontareitti,Virmo å paddlingsrutt,Mynäjoki paddling route,Mynämäki,Turun seutu,Varsinais-Suomi,Maakuntakaavan suunniteltu melontareitti,En planerad paddlingsrutt i landskapsplanen,A planned paddlings route in the regional land...,None,39500,None,None,None,None,None,None,ei tietoa ylläpitäjästä,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,503,23,02,F,None,None,False,notknown,False,NaN,NaN,97077,4451,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,97077,97077,Mynäjoentie,23100,Mynämäki,503,Mynämäki,None,2,Melontareitti,Paddlingsled,Canoe route,Mynäjoen melontareitti,None,None,None,+358401234567,Ei tietoa,Ei tietoa,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[222512.84...",221524.143730,6.732327e+06,1.001
131,26,26.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Nunnavuoren kuntorata,None,None,Turku,Turun seutu,Varsinais-Suomi,"1,7 km pitkä valaistu kuntoreitti. Talvella la...",None,None,None,2100,None,https://www.turku.fi/kulttuuri-ja-liikunta/lii...,None,None,None,None,Turun kaupunki,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,853,23,02,F,None,None,False,notknown,False,NaN,NaN,520340,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,520340,520340,Kurrapolku 8,20320,Turku,853,Turku,None,1,Kuntorata,Konditionsbana,Jogging track,Nunnavuoren kuntorata,Nunnebergets motionsbana,http://www.turku.fi/vapaa-aika/liikunta/ulkoli...,erkki@esimerkki.fi,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[239318.28...",239600.849578,6.714672e+06,1.032
137,31,31.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Viitankruunun muinaispolku,None,None,Salo,Salon seutu,Varsinais-Suomi,Viitamäen luontopolun varrella on muinaisia ra...,None,None,None,500,None,http://www.salo.fi/attachements/2018-03-15T12-...,None,None,None,None,None,None,ei ylläpitoa,None,None,None,2021/01/01,"LN, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,NaN,NaN,601682,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,601682,601682,Merikulmantie 259,24130,Salo,734,Salo,Viitankruunun muinaispolku lähtee Merikulmanti...,2,Luontopolku,Naturstig,Nature trail,Viitankruunun muinaispolku,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[284181,66...",284180.000000,6.697812e+06,1.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,472,472.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Rauhalinnan luontopolku helppokulkuinen,None,None,Kaarina,Turun seutu,Varsinais-Suomi,None,None,None,None,810,None,https://kaarina.fi/fi/asuminen-ja-ymparisto/ym...,None,None,erkki@esimerkki.fi,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,NaN,NaN,605786,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,605786,605786,Iso-Rauhalinnantie,20780,Kaarina,202,Kaarina,None,1,Luontopolku,Naturstig,Nature trail,Rauhalinnan luontopolku helppokulkuinen,None,https://kaarina.fi/fi/asuminen-ja-ymparisto/ym...,erkki@esimerkki.fi,None,Kunta,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246588.22...",246558.140768,6.705047e+06,1.021
1133,473,473.0,Virkistysreitti,Rekreationsrutt,Recreational route,Retkeilyreitti,Vandringsled,Hiking trail,Paavonpolut: Rautatiesilta-Halistenkoski,None,None,Turku,Turun seutu,Varsinais-Suomi,Paavonpolut on merkitty sinisillä merkeillä. M...,None,None,None,4260,None,https://www.turku.fi/vapaa-aika/ulkoilualueet/...,None,None,None,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2022/03/30,AKos,None,853,23,02,F,None,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,NaN,NaN,525507,4405,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,525507,525507,Turku,20100,Turku,853,Turku,Paavonpolut on merkitty sinisillä merkeillä. M...,85,Retkeilyreitti,Utflyktsled,Hiking route,Paavonpolut,None,https://www.turku.fi/vapaa-aika/ulkoilualueet/...,None,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240482.28...",241206.017965,6.712443e+06,1.004
1244,302490,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,NaN,NaN,528520,4402,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,528520,528520,Länsiniementie 101,25700,Kemiö,322,Kemiönsaari,"Lenkit 1,5 km ja 2,5 km.",2,Hiihtolatu,Skidspår,Ski track,Vretan Långdalenin latu,Vreta Långdalens skidspår,www.ksf.sporttisaitti.com,None,None,Rekisteröity yhdistys,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260646.78...",260500.922442,6.677761e+06,1.104
1337,302522,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,NaN,NaN,528520,4402,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,528520,528520,Länsiniementie 101,25700,Kemiö,322,Kemiönsaari,"Lenkit 1,5 km ja 2,5 km.",2,Hiihtolatu,Skidspår,Ski track,Vretan Långdalenin latu,Vreta Långdalens skidspår,www.ksf.sporttisaitti.com,None,None,Rekisteröity yhdistys,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260646.78...",260500.922442,6.677761e+06,1.104
1519,305918,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Aurajoen pyhiinvaelluspolut - Helenan polku,None,None,Turku,Turku,Varsinais-Suomi,Noin 8 km pituinen Helenan polku sopii kuljett...,None,None,None,220,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,None,None,erkki@esimerkki.fi,None,None,None,ei tietoa ylläpitoluokasta,None,2024/09/17,None,2024/09/17,NR,Pyhiinvaellus,853,023,02,F,None,https://citynomadi.com/api/media/caTD6s9Q_lM8vd,False,notknown,False,NaN,NaN,612929,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,612929,612929,Hämeenkatu 13,20500,Turku,853,Turku,Noin 8 km pituinen Helenan polku sopii kuljett...,1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Helenan polku,Helenas väg,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,erkki@esimerkki.fi,+358401234567,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240345.85...",241055.483622,6.712309e+06,1.000

In [16]:
summed_df.loc[
    (summed_df['overlap_ratio'] >= 1) &
    (summed_df['tyyppi_nimi_fi'] == summed_df['class2_fi'].map(mapping_dict)),
    'lipas_id'
] = summed_df['id_2']

In [17]:
summed_df = summed_df[
    (~summed_df['gid'].isin(summed_df.loc[summed_df['lipas_id'].notna() & (summed_df['lipas_id'] != 0), 'gid']))
    | ((summed_df['lipas_id'].notna()) & (summed_df['lipas_id'] != 0))
].copy()

In [18]:
summed_df.loc[ (summed_df['overlap_ratio'] >= 1) & (summed_df['tyyppi_nimi_fi'] == summed_df['class2_fi'].map(mapping_dict)) ]

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio
14,11,11.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Loukinaisten kuntorata,None,None,Lieto,Turun seutu,Varsinais-Suomi,"2,1 km pitkä valaistu kuntorata. Talvisin kunt...",None,None,None,2200,None,http://www.lieto.fi/,None,None,None,None,Liedon kunta,None,ei tietoa ylläpitoluokasta,None,None,None,2022/11/14,tuomohy,None,423,23,02,F,None,None,False,notknown,False,515096.0,NaN,515096,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,515096,515096,Airikintie,21410,Vanhalinna,423,Lieto,Talvikaudella kävely ja ulkoilu. Ei latua.,7,Kuntorata,Konditionsbana,Jogging track,Loukinaisten valaistu ulkoilurata,None,http://www.lieto.fi/,None,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[247163.76...",247188.208809,6.713565e+06,1.059
103,20,20.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Pöytyän Riihikosken urheilupuiston kuntorata,Riihikoski i Pöytis motionsbana,Pöytyä Riihikoski fitness trail,Pöytyä,Loimaan seutu,Varsinais-Suomi,Valaistu 1 km kuntorata. Maapohjan omistaa Pöy...,Upplyst 1 km motionsbana,1 km fitness trail with public lightning.,None,1000,None,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,None,None,Pöytyän kunta,None,ei tietoa ylläpitoluokasta,None,None,None,2023/08/22,LN,None,636,25,02,F,None,None,False,notknown,False,95745.0,NaN,95745,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,95745,95745,Yläneentie 14,21870,Riihikoski,636,Pöytyä,None,1,Kuntorata,Konditionsbana,Jogging track,Riihikosken kuntorata,None,None,None,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[259734.77...",259577.326500,6.739808e+06,1.000
124,23,23.0,Virkistysreitti,Rekreationsrutt,Recreational route,Melontareitti,Paddlingsrutt,Canoeing route,Mynäjoen melontareitti,Virmo å paddlingsrutt,Mynäjoki paddling route,Mynämäki,Turun seutu,Varsinais-Suomi,Maakuntakaavan suunniteltu melontareitti,En planerad paddlingsrutt i landskapsplanen,A planned paddlings route in the regional land...,None,39500,None,None,None,None,None,None,ei tietoa ylläpitäjästä,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,503,23,02,F,None,None,False,notknown,False,97077.0,NaN,97077,4451,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,97077,97077,Mynäjoentie,23100,Mynämäki,503,Mynämäki,None,2,Melontareitti,Paddlingsled,Canoe route,Mynäjoen melontareitti,None,None,None,+358401234567,Ei tietoa,Ei tietoa,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[222512.84...",221524.143730,6.732327e+06,1.001
131,26,26.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Nunnavuoren kuntorata,None,None,Turku,Turun seutu,Varsinais-Suomi,"1,7 km pitkä valaistu kuntoreitti. Talvella la...",None,None,None,2100,None,https://www.turku.fi/kulttuuri-ja-liikunta/lii...,None,None,None,None,Turun kaupunki,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,853,23,02,F,None,None,False,notknown,False,520340.0,NaN,520340,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,520340,520340,Kurrapolku 8,20320,Turku,853,Turku,None,1,Kuntorata,Konditionsbana,Jogging track,Nunnavuoren kuntorata,Nunnebergets motionsbana,http://www.turku.fi/vapaa-aika/liikunta/ulkoli...,erkki@esimerkki.fi,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[239318.28...",239600.849578,6.714672e+06,1.032
137,31,31.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Viitankruunun muinaispolku,None,None,Salo,Salon seutu,Varsinais-Suomi,Viitamäen luontopolun varrella on muinaisia ra...,None,None,None,500,None,http://www.salo.fi/attachements/2018-03-15T12-...,None,None,None,None,None,None,ei ylläpitoa,None,None,None,2021/01/01,"LN, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,601682.0,NaN,601682,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,601682,601682,Merikulmantie 259,24130,Salo,734,Salo,Viitankruunun muinaispolku lähtee Merikulmanti...,2,Luontopolku,Naturstig,Nature trail,Viitankruunun muinaispolku,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[284181,66...",284180.000000,6.697812e+06,1.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,472,472.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Rauhalinnan luontopolku helppokulkuinen,None,None,Kaarina,Turun seutu,Varsinais-Suomi,None,None,None,None,810,None,https://kaarina.fi/fi/asuminen-ja-ymparisto/ym...,None,None,erkki@esimerkki.fi,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,605786.0,NaN,605786,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,605786,605786,Iso-Rauhalinnantie,20780,Kaarina,202,Kaarina,None,1,Luontopolku,Naturstig,Nature trail,Rauhalinnan luontopolku helppokulkuinen,None,https://kaarina.fi/fi/asuminen-ja-ymparisto/ym...,erkki@esimerkki.fi,None,Kunta,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246588.22...",246558.140768,6.705047e+06,1.021
1133,473,473.0,Virkistysreitti,Rekreationsrutt,Recreational route,Retkeilyreitti,Vandringsled,Hiking trail,Paavonpolut: Rautatiesilta-Halistenkoski,None,None,Turku,Turun seutu,Varsinais-Suomi,Paavonpolut on merkitty sinisillä merkeillä. M...,None,None,None,4260,None,https://www.turku.fi/vapaa-aika/ulkoilualueet/...,None,None,None,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2022/03/30,AKos,None,853,23,02,F,None,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,525507.0,NaN,525507,4405,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,525507,525507,Turku,20100,Turku,853,Turku,Paavonpolut on merkitty sinisillä merkeillä. M...,85,Retkeilyreitti,Utflyktsled,Hiking route,Paavonpolut,None,https://www.turku.fi/vapaa-aika/ulkoilualueet/...,None,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240482.28...",241206.017965,6.712443e+06,1.004
1244,302490,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,528520.0,NaN,528520,4402,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,528520,528520,Länsiniementie 101,25700,Kemiö,322,Kemiönsaari,"Lenkit 1,5 km ja 2,5 km.",2,Hiihtolatu,Skidspår,Ski track,Vretan Långdalenin latu,Vreta Långdalens skidspår,www.ksf.sporttisaitti.com,None,None,Rekisteröity yhdistys,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260646.78...",260500.922442,6.677761e+06,1.104
1337,302522,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,528520.0,NaN,528520,4402,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,528520,528520,Länsiniementie 101,25700,Kemiö,322,Kemiönsaari,"Lenkit 1,5 km ja 2,5 km.",2,Hiihtolatu,Skidspår,Ski track,Vretan Långdalenin latu,Vreta Långdalens skidspår,www.ksf.sporttisaitti.com,None,None,Rekisteröity yhdistys,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260646.78...",260500.922442,6.677761e+06,1.104
1519,305918,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Aurajoen pyhiinvaelluspolut - Helenan polku,None,None,Turku,Turku,Varsinais-Suomi,Noin 8 km pituinen Helenan polku sopii kuljett...,None,None,None,220,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,None,None,erkki@esimerkki.fi,None,None,None,ei tietoa ylläpitoluokasta,None,2024/09/17,None,2024/09/17,NR,Pyhiinvaellus,853,023,02,F,None,https://citynomadi.com/api/media/caTD6s9Q_lM8vd,False,notknown,False,612929.0,NaN,612929,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,612929,612929,Hämeenkatu 13,20500,Turku,853,Turku,Noin 8 km pituinen Helenan polku sopii kuljett...,1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Helenan polku,Helenas väg,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,erkki@esimerkki.fi,+358401234567,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240345.85...",241055.483622,6.712309e+06,1.000

In [19]:
matched_routes = summed_df.loc[
    (summed_df['lipas_id'].notna()) & (summed_df['lipas_id'] != 0)
].copy()
matched_routes

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio
14,11,11.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Loukinaisten kuntorata,None,None,Lieto,Turun seutu,Varsinais-Suomi,"2,1 km pitkä valaistu kuntorata. Talvisin kunt...",None,None,None,2200,None,http://www.lieto.fi/,None,None,None,None,Liedon kunta,None,ei tietoa ylläpitoluokasta,None,None,None,2022/11/14,tuomohy,None,423,23,02,F,None,None,False,notknown,False,515096.0,NaN,515096,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,515096,515096,Airikintie,21410,Vanhalinna,423,Lieto,Talvikaudella kävely ja ulkoilu. Ei latua.,7,Kuntorata,Konditionsbana,Jogging track,Loukinaisten valaistu ulkoilurata,None,http://www.lieto.fi/,None,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[247163.76...",247188.208809,6.713565e+06,1.059
103,20,20.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Pöytyän Riihikosken urheilupuiston kuntorata,Riihikoski i Pöytis motionsbana,Pöytyä Riihikoski fitness trail,Pöytyä,Loimaan seutu,Varsinais-Suomi,Valaistu 1 km kuntorata. Maapohjan omistaa Pöy...,Upplyst 1 km motionsbana,1 km fitness trail with public lightning.,None,1000,None,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,None,None,Pöytyän kunta,None,ei tietoa ylläpitoluokasta,None,None,None,2023/08/22,LN,None,636,25,02,F,None,None,False,notknown,False,95745.0,NaN,95745,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,95745,95745,Yläneentie 14,21870,Riihikoski,636,Pöytyä,None,1,Kuntorata,Konditionsbana,Jogging track,Riihikosken kuntorata,None,None,None,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[259734.77...",259577.326500,6.739808e+06,1.000
124,23,23.0,Virkistysreitti,Rekreationsrutt,Recreational route,Melontareitti,Paddlingsrutt,Canoeing route,Mynäjoen melontareitti,Virmo å paddlingsrutt,Mynäjoki paddling route,Mynämäki,Turun seutu,Varsinais-Suomi,Maakuntakaavan suunniteltu melontareitti,En planerad paddlingsrutt i landskapsplanen,A planned paddlings route in the regional land...,None,39500,None,None,None,None,None,None,ei tietoa ylläpitäjästä,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,503,23,02,F,None,None,False,notknown,False,97077.0,NaN,97077,4451,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,97077,97077,Mynäjoentie,23100,Mynämäki,503,Mynämäki,None,2,Melontareitti,Paddlingsled,Canoe route,Mynäjoen melontareitti,None,None,None,+358401234567,Ei tietoa,Ei tietoa,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[222512.84...",221524.143730,6.732327e+06,1.001
131,26,26.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Nunnavuoren kuntorata,None,None,Turku,Turun seutu,Varsinais-Suomi,"1,7 km pitkä valaistu kuntoreitti. Talvella la...",None,None,None,2100,None,https://www.turku.fi/kulttuuri-ja-liikunta/lii...,None,None,None,None,Turun kaupunki,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,853,23,02,F,None,None,False,notknown,False,520340.0,NaN,520340,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,520340,520340,Kurrapolku 8,20320,Turku,853,Turku,None,1,Kuntorata,Konditionsbana,Jogging track,Nunnavuoren kuntorata,Nunnebergets motionsbana,http://www.turku.fi/vapaa-aika/liikunta/ulkoli...,erkki@esimerkki.fi,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[239318.28...",239600.849578,6.714672e+06,1.032
137,31,31.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Viitankruunun muinaispolku,None,None,Salo,Salon seutu,Varsinais-Suomi,Viitamäen luontopolun varrella on muinaisia ra...,None,None,None,500,None,http://www.salo.fi/attachements/2018-03-15T12-...,None,None,None,None,None,None,ei ylläpitoa,None,None,None,2021/01/01,"LN, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,601682.0,NaN,601682,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,601682,601682,Merikulmantie 259,24130,Salo,734,Salo,Viitankruunun muinaispolku lähtee Merikulmanti...,2,Luontopolku,Naturstig,Nature trail,Viitankruunun muinaispolku,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[284181,66...",284180.000000,6.697812e+06,1.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,472,472.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Rauhalinnan luontopolku helppokulkuinen,None,None,Kaarina,Turun seutu,Varsinais-Suomi,None,None,None,None,810,None,https://kaarina.fi/fi/asuminen-ja-ymparisto/ym...,None,None,erkki@esimerkki.fi,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,605786.0,NaN,605786,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,605786,605786,Iso-Rauhalinnantie,20780,Kaarina,202,Kaarina,None,1,Luontopolku,Naturstig,Nature trail,Rauhalinnan luontopolku helppokulkuinen,None,https://kaarina.fi/fi/asuminen-ja-ymparisto/ym...,erkki@esimerkki.fi,None,Kunta,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246588.22...",246558.140768,6.705047e+06,1.021
1133,473,473.0,Virkistysreitti,Rekreationsrutt,Recreational route,Retkeilyreitti,Vandringsled,Hiking trail,Paavonpolut: Rautatiesilta-Halistenkoski,None,None,Turku,Turun seutu,Varsinais-Suomi,Paavonpolut on merkitty sinisillä merkeillä. M...,None,None,None,4260,None,https://www.turku.fi/vapaa-aika/ulkoilualueet/...,None,None,None,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2022/03/30,AKos,None,853,23,02,F,None,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,525507.0,NaN,525507,4405,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,525507,525507,Turku,20100,Turku,853,Turku,Paavonpolut on merkitty sinisillä merkeillä. M...,85,Retkeilyreitti,Utflyktsled,Hiking route,Paavonpolut,None,https://www.turku.fi/vapaa-aika/ulkoilualueet/...,None,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240482.28...",241206.017965,6.712443e+06,1.004
1244,302490,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,528520.0,NaN,528520,4402,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,528520,528520,Länsiniementie 101,25700,Kemiö,322,Kemiönsaari,"Lenkit 1,5 km ja 2,5 km.",2,Hiihtolatu,Skidspår,Ski track,Vretan Långdalenin latu,Vreta Långdalens skidspår,www.ksf.sporttisaitti.com,None,None,Rekisteröity yhdistys,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260646.78...",260500.922442,6.677761e+06,1.104
1337,302522,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Vretan latu,Vreta skidspår,Vreta skitrack,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Lenkit 1,5 km ja 2,5 km. Tarkista ladun kunto:...","1,5 km och 2,5 km. På internettjänsten http://...",1.5 and 2.5 km. Check the current status: http...,None,1370,None,None,None,None,None,None,Kimitoöns kommun,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,528520.0,NaN,528520,4402,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,528520,528520,Länsiniementie 101,25700,Kemiö,322,Kemiönsaari,"Lenkit 1,5 km ja 2,5 km.",2,Hiihtolatu,Skidspår,Ski track,Vretan Långdalenin latu,Vreta Långdalens skidspår,www.ksf.sporttisaitti.com,None,None,Rekisteröity yhdistys,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[260646.78...",260500.922442,6.677761e+06,1.104
1519,305918,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Aurajoen pyhiinvaelluspolut - Helenan polku,None,None,Turku,Turku,Varsinais-Suomi,Noin 8 km pituinen Helenan polku sopii kuljett...,None,None,None,220,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,None,None,erkki@esimerkki.fi,None,None,None,ei tietoa ylläpitoluokasta,None,2024/09/17,None,2024/09/17,NR,Pyhiinvaellus,853,023,02,F,None,https://citynomadi.com/api/media/caTD6s9Q_lM8vd,False,notknown,False,612929.0,NaN,612929,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,612929,612929,Hämeenkatu 13,20500,Turku,853,Turku,Noin 8 km pituinen Helenan polku sopii kuljett...,1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Helenan polku,Helenas väg,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,erkki@esimerkki.fi,+358401234567,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240345.85...",241055.483622,6.712309e+06,1.000

In [20]:
summed_df = summed_df.drop(matched_routes.index)

In [21]:
summed_df = summed_df.reset_index(drop=True)
matched_routes = matched_routes.reset_index(drop=True)

In [22]:
pd.set_option('display.max_rows', None)
summed_df.loc[(summed_df["overlap_ratio"] > 0.4) & (summed_df["overlap_ratio"] < 0.5), ["name_fi", "nimi_fi", "overlap_ratio", "class2_fi", "tyyppi_nimi_fi"]]

,name_fi,nimi_fi,overlap_ratio,class2_fi,tyyppi_nimi_fi
86,Aurajoen melontareitti,Aurajoen melontareitti,0.448,Melontareitti,Melontareitti
133,Rankkulan kuntorata,Rankkulan latu,0.411,Kuntoreitti,Hiihtolatu
150,Sivurannikkoreitti: Högsåra,Rannikkoreitti,0.428,Pyöräilyreitti,Pyöräilyreitti
174,Urheilupuisto-Rivonmäenreitti -yhdysreitti,Paimion polku,0.413,Retkeilyreitti,Retkeilyreitti
178,Urheilupuisto-Rivonmäenreitti -yhdysreitti,Paimion polun talvireitti,0.413,Retkeilyreitti,Retkeilyreitti
232,Halikonlahden lintupolku ja esteetön polku,Halikonlahden esteetön polku,0.495,Luontopolku,Luontopolku
334,Paimionjoen melontareitti,Paimiojoen melontareitti,0.456,Melontareitti,Melontareitti
351,Rivonmäen reitti - lyhyempi reitti,"Rivonmäen reitti, talvikävely",0.457,Retkeilyreitti,Kävelyreitti/ulkoilureitti
395,Perniön Melassuon kuntorata,Melassuon valaistu latu,0.478,Kuntoreitti,Hiihtolatu
496,Orikedon kuntorata,Kuntorata Oriketo-Räntämäki,0.451,Kuntoreitti,Kuntorata
499,Orikedon kuntorata,Oriketo-Räntämäki,0.430,Kuntoreitti,Hiihtolatu
533,Kasnäsin retkeilyreitti 5-8 km,Högsåra pyöräillen,0.489,Retkeilyreitti,Pyöräilyreitti
573,Piiloleikki - etsi kätketyt pikkupatsaat,EuroVelo 10 - Itämeren reitti,0.449,Kulttuuriulkoilureitti,Pyöräilyreitti
574,Piiloleikki - etsi kätketyt pikkupatsaat,EuroVelo 10 - Turku-Helsinki,0.488,Kulttuuriulkoilureitti,Pyöräilyreitti
575,Piiloleikki - etsi kätketyt pikkupatsaat,EuroVelo 10 - Yyteri/Pori - Turku,0.468,Kulttuuriulkoilureitti,Pyöräilyreitti
590,Hiunjärven luontopolku,Hiunjärven ulkoilureitti,0.484,Luontopolku,Luontopolku
594,Asemanseudun luontopolku,Asemanseudun luontopolku,0.495,Retkeilyreitti,Retkeilyreitti
604,Suomen Sydän - aikamatka historiaan,Pietarin polku,0.479,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti
674,Paavonpolut (reitti 10D): Hirvensalo: Majamäki...,Paavonpolut,0.471,Kuntoreitti,Retkeilyreitti
762,Vanha Tampereentie pyöräilyn yhdysreitti,Kuuden kunnanosan kierros,0.439,Pyöräilyreitti,Pyöräilyreitti
872,Vuosnaisten luontopolku,Vuosnaisten luontopolku,0.493,Luontopolku,Luontopolku
875,"Raukkaankosken rantapolku, kanoottien maihinno...",Asemanseudun luontopolku,0.407,Retkeilyreitti,Retkeilyreitti
964,Lilla Masugnsträsketin luontopolku,Senatsberget hyvinvointipolku,0.425,Retkeilyreitti,Luontopolku
969,Stora Masugnsträsketin hiihtolatu,Stora Masugnsträsketin melontareitti,0.480,Latu,Melontareitti
983,Mona-polku,Purunpään retkeilyreitistö,0.466,Kulttuuriulkoilureitti,Retkeilyreitti
1012,Purunpään retkeilyreitti,Söderlångvik gravel,0.415,Retkeilyreitti,Pyöräilyreitti
1053,Stora Masugnsträsketin hiihtolatu,Stora Masugnsträsketin melontareitti,0.480,Latu,Melontareitti
1057,Lilla Masugnsträsketin luontopolku,Senatsberget hyvinvointipolku,0.425,Retkeilyreitti,Luontopolku
1072,Mona-polku,Purunpään retkeilyreitistö,0.466,Kulttuuriulkoilureitti,Retkeilyreitti
1155,Rannikkoreitti: Taalintehdas - Rosala 25 km,Rannikkoreitti,0.487,Pyöräilyreitti,Pyöräilyreitti
1169,Kuuden tuuman tarina,Rannikkoreitti,0.440,Luontopolku,Pyöräilyreitti
1171,Oinilan jokipolku,Oinilan jokipolku,0.482,Retkeilyreitti,Luontopolku
1190,Pietarin polku,Pietarin polku,0.466,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti
1191,Pietarin polku,Helenan polku,0.498,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti
1192,Pietarin polku,Pyhää kohti - keskiaikainen pyhiinvaellusreitt...,0.489,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti
1232,Luomakunnan huokaus meissä,Pietarin polku,0.466,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti
1233,Luomakunnan huokaus meissä,Helenan polku,0.498,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti
1234,Luomakunnan huokaus meissä,Pyhää kohti - keskiaikainen pyhiinvaellusreitt...,0.489,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti

In [23]:
summed_df.loc[
    (summed_df['overlap_ratio'] > 0.5) &
    (summed_df['tyyppi_nimi_fi'] == summed_df['class2_fi'].map(mapping_dict))
].shape

(164, 74)

In [24]:
summed_df.loc[
    (summed_df['overlap_ratio'] > 0.5) &
    (summed_df['tyyppi_nimi_fi'] == summed_df['class2_fi'].map(mapping_dict)),
    'lipas_id'
] = summed_df['id_2']

In [25]:
pd.reset_option('display.max_rows')
summed_df.loc[
    summed_df["lipas_id"].notna(),
    ["name_fi", "nimi_fi", "class2_fi", "tyyppi_nimi_fi"]
]

,name_fi,nimi_fi,class2_fi,tyyppi_nimi_fi
16,Ankka-Nautela luontopolku,Ankka-Nautela luontopolku,Luontopolku,Luontopolku
124,Puutarhan kierto,Ruissalon luontopolut,Luontopolku,Luontopolku
126,Metsäkoivulan polku,Metsäkoivulan polku,Luontopolku,Luontopolku
132,Hirvenpolku,Metsäkoivulan polku,Luontopolku,Luontopolku
134,Rankkulan kuntorata,Rankkulan pururata,Kuntoreitti,Kuntorata
...,...,...,...,...
1165,Rannikkoreitti: Tammisaari - Tenhola 18 km,EuroVelo 10 - Turku-Helsinki,Pyöräilyreitti,Pyöräilyreitti
1168,Lieto MTB XCO -maastopyörärata,Liedon XCO-rata,Maastopyöräilyreitti,Maastopyöräilyreitti
1170,Kuuden tuuman tarina,6 tuuman kierros,Luontopolku,Luontopolku
1194,Pietarin polku,Luomakunnan huokaus meissä - kaupunki pyhiinva...,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti
1236,Luomakunnan huokaus meissä,Luomakunnan huokaus meissä - kaupunki pyhiinva...,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti

In [26]:
summed_df = summed_df[
    (~summed_df['gid'].isin(summed_df.loc[summed_df['lipas_id'].notna() & (summed_df['lipas_id'] != 0), 'gid']))
    | ((summed_df['lipas_id'].notna()) & (summed_df['lipas_id'] != 0))
].copy()

summed_df.shape

(939, 74)

In [27]:
new_rows = summed_df.loc[
    (summed_df['lipas_id'].notna()) & (summed_df['lipas_id'] != 0)
].copy()


matched_routes = pd.concat([matched_routes, new_rows], ignore_index=True)

In [28]:
summed_df = summed_df.drop(new_rows.index)
summed_df.shape

(775, 74)

In [29]:
matched_routes

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio
0,11,11.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Loukinaisten kuntorata,None,None,Lieto,Turun seutu,Varsinais-Suomi,"2,1 km pitkä valaistu kuntorata. Talvisin kunt...",None,None,None,2200,None,http://www.lieto.fi/,None,None,None,None,Liedon kunta,None,ei tietoa ylläpitoluokasta,None,None,None,2022/11/14,tuomohy,None,423,23,02,F,None,None,False,notknown,False,515096.0,NaN,515096,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,515096,515096,Airikintie,21410,Vanhalinna,423,Lieto,Talvikaudella kävely ja ulkoilu. Ei latua.,7,Kuntorata,Konditionsbana,Jogging track,Loukinaisten valaistu ulkoilurata,None,http://www.lieto.fi/,None,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[247163.76...",247188.208809,6.713565e+06,1.059
1,20,20.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Pöytyän Riihikosken urheilupuiston kuntorata,Riihikoski i Pöytis motionsbana,Pöytyä Riihikoski fitness trail,Pöytyä,Loimaan seutu,Varsinais-Suomi,Valaistu 1 km kuntorata. Maapohjan omistaa Pöy...,Upplyst 1 km motionsbana,1 km fitness trail with public lightning.,None,1000,None,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,None,None,Pöytyän kunta,None,ei tietoa ylläpitoluokasta,None,None,None,2023/08/22,LN,None,636,25,02,F,None,None,False,notknown,False,95745.0,NaN,95745,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,95745,95745,Yläneentie 14,21870,Riihikoski,636,Pöytyä,None,1,Kuntorata,Konditionsbana,Jogging track,Riihikosken kuntorata,None,None,None,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[259734.77...",259577.326500,6.739808e+06,1.000
2,23,23.0,Virkistysreitti,Rekreationsrutt,Recreational route,Melontareitti,Paddlingsrutt,Canoeing route,Mynäjoen melontareitti,Virmo å paddlingsrutt,Mynäjoki paddling route,Mynämäki,Turun seutu,Varsinais-Suomi,Maakuntakaavan suunniteltu melontareitti,En planerad paddlingsrutt i landskapsplanen,A planned paddlings route in the regional land...,None,39500,None,None,None,None,None,None,ei tietoa ylläpitäjästä,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,503,23,02,F,None,None,False,notknown,False,97077.0,NaN,97077,4451,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,97077,97077,Mynäjoentie,23100,Mynämäki,503,Mynämäki,None,2,Melontareitti,Paddlingsled,Canoe route,Mynäjoen melontareitti,None,None,None,+358401234567,Ei tietoa,Ei tietoa,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[222512.84...",221524.143730,6.732327e+06,1.001
3,26,26.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Nunnavuoren kuntorata,None,None,Turku,Turun seutu,Varsinais-Suomi,"1,7 km pitkä valaistu kuntoreitti. Talvella la...",None,None,None,2100,None,https://www.turku.fi/kulttuuri-ja-liikunta/lii...,None,None,None,None,Turun kaupunki,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,853,23,02,F,None,None,False,notknown,False,520340.0,NaN,520340,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,520340,520340,Kurrapolku 8,20320,Turku,853,Turku,None,1,Kuntorata,Konditionsbana,Jogging track,Nunnavuoren kuntorata,Nunnebergets motionsbana,http://www.turku.fi/vapaa-aika/liikunta/ulkoli...,erkki@esimerkki.fi,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[239318.28...",239600.849578,6.714672e+06,1.032
4,31,31.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Viitankruunun muinaispolku,None,None,Salo,Salon seutu,Varsinais-Suomi,Viitamäen luontopolun varrella on muinaisia ra...,None,None,None,500,None,http://www.salo.fi/attachements/2018-03-15T12-...,None,None,None,None,None,None,ei ylläpitoa,None,None,None,2021/01/01,"LN, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,601682.0,NaN,601682,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,601682,601682,Merikulmantie 259,24130,Salo,734,Salo,Viitankruunun muinaispolku lähtee Merikulmanti...,2,Luontopolku,Naturstig,Nature trail,Viitankruunun muinaispolku,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[284181,66...",284180.000000,6.697812e+06,1.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,302592,NaN,Virkistysreitti,rekreationsrutt,recreational route,Pyöräilyreitti,cyklingsrutt,biking route,Rannikkoreitti: Tammisaari - Tenhola 18 km,Kustrutten: Ekenäs - Tenala 18 km,Coastal Route: Ekenäs - Tenala 18 km,Raasepori,Raasepori,Uusimaa,Käyskentele meren rantaan levittäytyvän Tammis...,Vandra omkring Ekenäs gamla stad längs de smal...,Wander around the old town of Ekenäs and along...,None,18000,None,https://www.bikeland.fi/rannikkoreitti,None,None,None,None,None,None,ei tietoa ylläpitoluokasta,None,2023/01/17,None,2023/01/18,sannamari,None,710,014,01,F,None,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,617406.0,NaN,617406,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617406,617406,Tullikatu 9,21100,Naantali,529,Naantali,None,5,Pyöräilyreitti,Cykelled,Biking route,EuroVelo 10 - Turku-Helsinki,None,None,None,None,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[287840.24...",295128.609941,6.659179e+06,0.750
277,305504,NaN,Virkistysreitti,rekreationsrutt,recreational route,Maastopyöräilyreitti,terrängcycklingsrutt,mountain biking route,Lieto MTB XCO -maastopyörärata,maastopyorareitti,maastopyorareitti,Parainen,Åboland-Turunmaa,Varsinais-Suomi,Rata on merkitty maastoon opasnuolin ja -kylte...,None,None,None,3020,None,None,None,None,None,None,None,None,ei ylläpitoa,None,2023/03/31,None,2025/02/06,"lamkoi, NR",None,445,021,02,F,None,None,False,notknown,False,527756.0,NaN,527756,4411,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,527756,527756,Urheilutie 2,21420,Lieto,423,Lieto,"Harrastajarata 3 km, kilpailurata 3,8 km. Yllä...",4,Maastopyöräilyreitti,Mountainbikeled,Cross-country biking route,Liedon XCO-rata,None,http://www.lieto.fi/fi-FI/Kulttuuri_ja_vapaaai...,erkki@esimerkki.fi,None,Kunta,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[250056.35...",250178.733749,6.715510e+06,0.993
278,305561,NaN,Virkistysreitti,rekreationsrutt,recreational route,Luontopolku,naturstig,nature trail,Kuuden tuuman tarina,"6 "" rundan","6 "" trail",Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,"Eteläisempi reitti Örön saarella, siniset heij...",None,None,None,1260,None,None,None,None,None,None,Metsähallitus,None,ajoittainen,None,2023/08/02,None,2023/08/02,sannamari,None,322,021,02,F,None,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,604955.0,NaN,604955,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,604955,604955,Örö,25930,None,322,Kemiönsaari,None,10,Luontopolku,Naturstig,Nature trail,6 tuuman kierros,6 tums rundan,None,erkki@esimerkki.fi,+358401234567,Valtio,Valtio,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[237208,66...",237201.500000,6.638827e+06,0.957
279,305911,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Pietarin polku,None,None,Turku,Turku,Varsinais-Suomi,Pyhiinvaellusreitti,None,None,None,3510,None,None,None,None,None,None,None,None,ei tietoa ylläpitoluokasta,None,2024/09/12,None,2024/09/12,NR,None,853,023,02,F,None,None,False,notknown,False,617619.0,NaN,617619,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617619,617619,Hämeenkatu 13,20500,Turku,853,Turku,"Tällä pienellä pyhiinvaelluksella (2,4 km) kul...",1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Luomakunnan huokaus meissä - kaupunki pyhiinva...,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,erkki@esimerkki.fi,+358401234567,Muu,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240353.64...",240367.502382,6.711501e+06,0.990
280,305916,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Luomakunnan huokaus meissä,None,None,Turku,Turku,Varsinais-Suomi,Kaupunkipyhiinvaellus. Tällä pienellä pyhiinva...,None,None,None,210,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,None,None,erkki@esimerkki.fi,None,None,None,ei tietoa ylläpitoluokasta,None,2024/09/17,None,2024/09/20,NR,Pyhiinvaellus,284,025,02,F,None,https://pyhiinvaellussuomi.fi/wp-content/uploa...,False,notknown,False,617619.0,NaN,617619,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617619,617619,Hämeenkatu 13,20500,Turku,853,Turku,"Tällä pienellä pyhiinvaelluksella (2,4 km) kul...",1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Luomakunnan huokaus meissä - kaupunki pyhiinva...,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,erkki@esimerkki.fi,+358401234567,Muu,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240353.64...",240367.502382,6.711501e+06,0.990

In [30]:
summed_df.loc[
    summed_df["overlap_ratio"] > 0.5,
    ["name_fi", "nimi_fi", "class2_fi", "tyyppi_nimi_fi", "overlap_ratio"]
]

,name_fi,nimi_fi,class2_fi,tyyppi_nimi_fi,overlap_ratio
1,Kuusiston koulupolku,Kuusiston koulupolku,Kuntoreitti,Kävelyreitti/ulkoilureitti,1.000
11,tuntematon 5,Ankka-Nautela luontopolku,Retkeilyreitti,Luontopolku,1.001
78,Paavonpolut: Yhdysreitti: Halinen-Oriketo,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.710
169,Vähäjokipolku,"Vähäjokipolku, talvikävely",Luontopolku,Kävelyreitti/ulkoilureitti,0.699
236,Paavonpolut (reitti 8): Uittamo-Katariinanlaakso,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.780
...,...,...,...,...,...
971,Kiilan latu,Kiilan kuntorata,Latu,Kuntorata,0.945
1056,Lilla Masugnsträsketin luontopolku,Pieni Masuuninjärvi,Retkeilyreitti,Kävelyreitti/ulkoilureitti,0.854
1060,Kiilan latu,Kiilan kuntorata,Latu,Kuntorata,0.945
1166,Vaisakko luontopolku,Vaisakon polku,Luontopolku,Retkeilyreitti,0.776
1245,Henrikin polku,Henrikin polku,Kulttuuriulkoilureitti,Pyöräilyreitti,0.980

In [31]:
from rapidfuzz import fuzz, process

# Compute fuzzy match scores
scores = [
    fuzz.token_sort_ratio(str(a), str(b))
    for a, b in zip(summed_df["name_fi"], summed_df["nimi_fi"])
]

# Add as a temporary column
summed_df["fuzz_score"] = scores
summed_df.head()

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio,fuzz_score
0,1,1.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Kuusiston linnanraunioiden pyöräilyreitti,None,None,Kaarina,Turun seutu,Varsinais-Suomi,Reitti on yhteen suuntaan 6 km ja edestakaisin...,None,None,None,590,None,http://www.reitisto.fi/kuusistonpyorailyreitti,None,None,erkki@esimerkki.fi,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,NaN,NaN,606780,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,606780,606780,Linnanrauniontie 556,21620,Kaarina,202,Kaarina,Reitti on yhteen suuntaan 6 km ja edestakaisin...,1,Pyöräilyreitti,Cykelled,Biking route,Kuusiston linnanraunioiden pyöräilyreitti,None,http://www.reitisto.fi/kuusistonpyorailyreitti,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246350.08...",248425.143461,6.703885e+06,0.019,100.000000
1,3,3.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Kuusiston koulupolku,None,None,Kaarina,Turun seutu,Varsinais-Suomi,None,None,None,None,1260,None,http://www.reitisto.fi/kuusistonkoulupolku,None,None,erkki@esimerkki.fi,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,NaN,NaN,605796,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,605796,605796,Pallotie 2 / Kuusiston koulutie 14,21620,Kuusisto,202,Kaarina,None,1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Kuusiston koulupolku,None,http://www.reitisto.fi/kuusistonkoulupolku,erkki@esimerkki.fi,None,Muu,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246664.09...",246216.536538,6.703447e+06,1.000,100.000000
2,4,4.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Rannikkoreitti,None,None,Salo,None,None,www.rannikkoreitti.fi,None,None,None,4910,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,None,None,None,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,NaN,NaN,604266,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,604266,604266,Engelsbyntie 8,25700,None,322,Kemiönsaari,None,33,Pyöräilyreitti,Cykelled,Biking route,Rannikkoreitti,Kustrutten,www.rannikkoreitti.fi,None,None,Kunta,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[285030.34...",279116.445549,6.687877e+06,0.061,100.000000
3,4,4.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Rannikkoreitti,None,None,Salo,None,None,www.rannikkoreitti.fi,None,None,None,4910,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,None,None,None,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,NaN,NaN,616807,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,616807,616807,Pakkahuoneenkatu,95400,Tornio,851,Tornio,None,1,Pyöräilyreitti,Cykelled,Biking route,EuroVelo 10 - Itämeren reitti,EuroVelo 10 - Baltic Sea Cycle Route,None,None,None,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[369864.68...",317309.074686,6.905632e+06,0.082,32.558140
4,4,4.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Rannikkoreitti,None,None,Salo,None,None,www.rannikkoreitti.fi,None,None,None,4910,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,None,None,None,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,NaN,NaN,617406,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617406,617406,Tullikatu 9,21100,Naantali,529,Naantali,None,2,Pyöräilyreitti,Cykelled,Biking route,EuroVelo 10 - Turku-Helsinki,None,None,None,None,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[276828.64...",275247.378348,6.684717e+06,0.066,23.809524

In [32]:
summed_df.loc[
    (summed_df['overlap_ratio'] > 0.5) &
    (summed_df["fuzz_score"] > 75)
].shape

(17, 75)

In [33]:
summed_df.loc[
    (summed_df['overlap_ratio'] > 0.5) &
    (summed_df["fuzz_score"] > 75),
    'lipas_id'
] = summed_df['id_2']

In [34]:
summed_df = summed_df[
    (~summed_df['gid'].isin(summed_df.loc[summed_df['lipas_id'].notna() & (summed_df['lipas_id'] != 0), 'gid']))
    | ((summed_df['lipas_id'].notna()) & (summed_df['lipas_id'] != 0))
].copy()

summed_df.shape

(755, 75)

In [35]:
new_rows = summed_df.loc[
    (summed_df['lipas_id'].notna()) & (summed_df['lipas_id'] != 0)
].copy()


matched_routes = pd.concat([matched_routes, new_rows], ignore_index=True)

In [36]:
summed_df = summed_df.drop(new_rows.index)
summed_df.shape

(738, 75)

In [37]:
summed_df.loc[
    summed_df["overlap_ratio"] > 0.5,
    ["name_fi", "nimi_fi", "class2_fi", "tyyppi_nimi_fi", "overlap_ratio"]
]

,name_fi,nimi_fi,class2_fi,tyyppi_nimi_fi,overlap_ratio
11,tuntematon 5,Ankka-Nautela luontopolku,Retkeilyreitti,Luontopolku,1.001
78,Paavonpolut: Yhdysreitti: Halinen-Oriketo,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.710
169,Vähäjokipolku,"Vähäjokipolku, talvikävely",Luontopolku,Kävelyreitti/ulkoilureitti,0.699
236,Paavonpolut (reitti 8): Uittamo-Katariinanlaakso,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.780
239,Paavonpolut (reitti 10A): Hirvensalo: Moikoine...,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.689
255,Paavonpolut (reitti 7): Luolavuori-Uittamo-Pui...,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.725
274,Harjureitin retkeilyreitti ja valaisematon latu,Harjureitti,Retkeilyreitti,Luontopolku,0.781
276,Paavonpolut (reitti 1): Pansio-Perno,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.564
283,Paavonpolut (reitti 3): Runosmäki-Pomponrahka,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.805
296,Kirjaisten Gloetin reitti,Kirjaisten luontopolut,Retkeilyreitti,Luontopolku,1.024
298,Paavonpolut (reitti 4): Kohmo-Kurala,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.847
301,Paavonpolut (reitti 2): Suikkila-Vätti-Kähäri-...,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.885
307,Paavonpolut: Yhdysreitti: Perno-Suikkila,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.838
324,Paavonpolut (reitti 6): Koivula-Harittu-Skanssi,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.787
337,Paavonpolut (reitti 10C): Hirvensalo: Kukola-M...,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.631
360,Paavonpolut (reitti 9): Maaria,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.729
391,Ruskon rantapolku,Rantapolku,Kuntoreitti,Kävelyreitti/ulkoilureitti,0.734
393,Raision Jokipolku,Vaskipolku,Kulttuuriulkoilureitti,Retkeilyreitti,0.860
454,Vaskireitti,Vaskipolku,Luontopolku,Retkeilyreitti,0.649
483,Finbyn jatulintarhan ja kirkonmäen luontopolku,Nauvon kävelyreitit,Luontopolku,Kävelyreitti/ulkoilureitti,0.920
492,Paimion muurahaispolku,Muurahaispolku,Luontopolku,Kävelyreitti/ulkoilureitti,1.000
505,Koroistenniemen polku,Pietarin polku,Luontopolku,Kävelyreitti/ulkoilureitti,0.857
506,Koroistenniemen polku,Helenan polku,Luontopolku,Kävelyreitti/ulkoilureitti,0.917
515,Kultaranta Resortin Kuru-ulkoilureitistö: Ketu...,Aurinkokurun retkeilyreitti,Retkeilyreitti,Kävelyreitti/ulkoilureitti,0.864
520,Kultaranta Resortin Kuru-ulkoilureitistö: Ilve...,Aurinkokurun retkeilyreitti,Retkeilyreitti,Kävelyreitti/ulkoilureitti,0.804
521,Kultaranta Resortin Kuru-ulkoilureitistö: Aven...,Aurinkokurun retkeilyreitti,Retkeilyreitti,Kävelyreitti/ulkoilureitti,0.840
530,Kasnäsin retkeilyreitti 5-8 km,Kasnäsin ulkoilureitit,Retkeilyreitti,Kävelyreitti/ulkoilureitti,0.795
595,Maskun Rivieran kuntoreitti,Rivieran ulkoilureitti,Kuntoreitti,Kävelyreitti/ulkoilureitti,0.938
597,Maskun Rivieran kuntoreitti,Rivieran ladut,Kuntoreitti,Hiihtolatu,0.703
619,Harjureitin retkeilyreitti ja valaistu latu,Harjureitti,Retkeilyreitti,Luontopolku,0.749
654,Paavonpolut (reitti 5): Varissuo-Pääskyvuori,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.676
656,Paavonpolut: Yhdysreitti: Raunistula,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.931
661,Paavonpolut: Yhdysreitti: Vätti-Impivaara,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.958
671,Paavonpolut (reitti 10B): Hirvensalo: Golf-ken...,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.650
687,Kerttula-Petäsmäki -yhdysreitti,Kerttulan ja Petäsmäen yhdyslatu,Kuntoreitti,Hiihtolatu,1.068
706,Nauvon kirkonkylän luontopolku ja Nauvo-Nallen...,Nauvon kävelyreitit,Luontopolku,Kävelyreitti/ulkoilureitti,1.013
708,Metsämaan retkeilyreitti,Metsämaan luontopolku,Retkeilyreitti,Luontopolku,1.003
713,Oinilan maauimalan kuntorata,Oinilan hiihtolatu,Kuntoreitti,Hiihtolatu,0.609
714,Oinilan maauimalan kuntorata,Oinilan talvikävelyreitti,Kuntoreitti,Kävelyreitti/ulkoilureitti,0.890
760,Aurajoentien matkailutie,Turusta Alpo Jaakolan patsaspuiston kautta Loi...,Matkailureitti,Pyöräilyreitti,0.709
772,tuntematon,Ankka-Nautela luontopolku,Retkeilyreitti,Luontopolku,1.044
866,Piikkiön Linnavuoren luontopolku,Piikkiön Linnavuoren retkeilyreitti,Luontopolku,Retkeilyreitti,0.999
963,Lilla Masugnsträsketin luontopolku,Pieni Masuuninjärvi,Retkeilyreitti,Kävelyreitti/ulkoilureitti,0.854
971,Kiilan latu,Kiilan kuntorata,Latu,Kuntorata,0.945
1056,Lilla Masugnsträsketin luontopolku,Pieni Masuuninjärvi,Retkeilyreitti,Kävelyreitti/ulkoilureitti,0.854
1060,Kiilan latu,Kiilan kuntorata,Latu,Kuntorata,0.945

In [38]:
summed_df.loc[
    (summed_df["overlap_ratio"] > 0.5)
    & (~summed_df["class2_fi"].isin(["Latu", "Retkilatu"]))
    & (~summed_df["tyyppi_nimi_fi"].isin(["Latu", "Hiihtolatu"]))
].shape

(41, 75)

In [39]:
summed_df.loc[
    (summed_df["overlap_ratio"] > 0.5)
    & (~summed_df["class2_fi"].isin(["Latu", "Retkilatu"]))
    & (~summed_df["tyyppi_nimi_fi"].isin(["Latu", "Hiihtolatu"])),
    'lipas_id'
] = summed_df['id_2']

In [40]:
summed_df = summed_df[
    (~summed_df['gid'].isin(summed_df.loc[summed_df['lipas_id'].notna() & (summed_df['lipas_id'] != 0), 'gid']))
    | ((summed_df['lipas_id'].notna()) & (summed_df['lipas_id'] != 0))
].copy()

summed_df.shape

(644, 75)

In [41]:
new_rows = summed_df.loc[
    (summed_df['lipas_id'].notna()) & (summed_df['lipas_id'] != 0)
].copy()


matched_routes = pd.concat([matched_routes, new_rows], ignore_index=True)

In [42]:
summed_df = summed_df.drop(new_rows.index)
summed_df.shape

(603, 75)

In [43]:
summed_df.loc[
    (summed_df["fuzz_score"] > 0.6)
    & (summed_df["overlap_ratio"] > 0.4),
    ["name_fi", "nimi_fi", "class2_fi", "tyyppi_nimi_fi", "overlap_ratio", "fuzz_score"]
]

,name_fi,nimi_fi,class2_fi,tyyppi_nimi_fi,overlap_ratio,fuzz_score
86,Aurajoen melontareitti,Aurajoen melontareitti,Melontareitti,Melontareitti,0.448,100.000000
573,Piiloleikki - etsi kätketyt pikkupatsaat,EuroVelo 10 - Itämeren reitti,Kulttuuriulkoilureitti,Pyöräilyreitti,0.449,34.782609
574,Piiloleikki - etsi kätketyt pikkupatsaat,EuroVelo 10 - Turku-Helsinki,Kulttuuriulkoilureitti,Pyöräilyreitti,0.488,29.411765
575,Piiloleikki - etsi kätketyt pikkupatsaat,EuroVelo 10 - Yyteri/Pori - Turku,Kulttuuriulkoilureitti,Pyöräilyreitti,0.468,24.657534
590,Hiunjärven luontopolku,Hiunjärven ulkoilureitti,Luontopolku,Luontopolku,0.484,65.217391
594,Asemanseudun luontopolku,Asemanseudun luontopolku,Retkeilyreitti,Retkeilyreitti,0.495,100.000000
604,Suomen Sydän - aikamatka historiaan,Pietarin polku,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,0.479,24.489796
674,Paavonpolut (reitti 10D): Hirvensalo: Majamäki...,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.471,33.846154
687,Kerttula-Petäsmäki -yhdysreitti,Kerttulan ja Petäsmäen yhdyslatu,Kuntoreitti,Hiihtolatu,1.068,47.619048
872,Vuosnaisten luontopolku,Vuosnaisten luontopolku,Luontopolku,Luontopolku,0.493,100.000000
875,"Raukkaankosken rantapolku, kanoottien maihinno...",Asemanseudun luontopolku,Retkeilyreitti,Retkeilyreitti,0.407,37.974684
971,Kiilan latu,Kiilan kuntorata,Latu,Kuntorata,0.945,66.666667
1060,Kiilan latu,Kiilan kuntorata,Latu,Kuntorata,0.945,66.666667
1155,Rannikkoreitti: Taalintehdas - Rosala 25 km,Rannikkoreitti,Pyöräilyreitti,Pyöräilyreitti,0.487,49.122807
1171,Oinilan jokipolku,Oinilan jokipolku,Retkeilyreitti,Luontopolku,0.482,100.000000

In [44]:
low_overlap_gids = (
    summed_df.groupby("gid")["overlap_ratio"]
    .max()  # if max < 0.1, then all rows are < 0.1
    .loc[lambda x: x < 0.2]
    .index
)

In [45]:
low_overlap_gids

Index([     1,      4,      5,     15,     16,     21,     25,     34,     37,
           43,     49,     57,     60,     61,     62,     67,     89,    109,
          119,    127,    131,    134,    135,    140,    156,    160,    161,
          170,    187,    218,    223,    225,    227,    239,    260,    261,
          267,    270,    276,    284,    286,    290,    298,    311,    329,
          331,    332,    350,    357,    386,    411,    416,    425,    426,
          434,    435,    438,    439,    446,    454,    455, 302224, 302264,
       302295, 302297, 302309, 302316, 302322, 302378, 302379, 302471, 302472,
       302473, 302476, 302477, 302479, 302480, 302481, 302502, 302503, 302505,
       302508, 302509, 302510, 302511, 302513, 302591, 305856, 305994],
      dtype='int64', name='gid')

In [46]:
low_overlap_rows = summed_df[summed_df["gid"].isin(low_overlap_gids)].copy()

best_low_overlap_rows = (
    low_overlap_rows.sort_values("overlap_ratio", ascending=False)
    .groupby("gid", as_index=False)
    .first()
)

In [47]:
best_low_overlap_rows["lipas_id"] = 0
best_low_overlap_rows.head()

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio,fuzz_score
0,1,1.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Kuusiston linnanraunioiden pyöräilyreitti,None,None,Kaarina,Turun seutu,Varsinais-Suomi,Reitti on yhteen suuntaan 6 km ja edestakaisin...,None,None,None,590,None,http://www.reitisto.fi/kuusistonpyorailyreitti,None,None,erkki@esimerkki.fi,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,0,NaN,606780,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,606780,606780,Linnanrauniontie 556,21620,Kaarina,202,Kaarina,Reitti on yhteen suuntaan 6 km ja edestakaisin...,1,Pyöräilyreitti,Cykelled,Biking route,Kuusiston linnanraunioiden pyöräilyreitti,None,http://www.reitisto.fi/kuusistonpyorailyreitti,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246350.08...",248425.143461,6.703885e+06,0.019,100.000000
1,4,4.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Rannikkoreitti,None,None,Salo,None,None,www.rannikkoreitti.fi,None,None,None,4910,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,None,None,None,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,0,NaN,616807,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,616807,616807,Pakkahuoneenkatu,95400,Tornio,851,Tornio,None,1,Pyöräilyreitti,Cykelled,Biking route,EuroVelo 10 - Itämeren reitti,EuroVelo 10 - Baltic Sea Cycle Route,www.rannikkoreitti.fi,None,None,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[369864.68...",317309.074686,6.905632e+06,0.082,32.558140
2,5,5.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Rannikkoreitti,None,None,Salo,None,None,www.rannikkoreitti.fi,None,None,None,2700,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,None,None,None,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,0,NaN,617406,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617406,617406,Tullikatu 9,21100,Naantali,529,Naantali,None,2,Pyöräilyreitti,Cykelled,Biking route,EuroVelo 10 - Turku-Helsinki,Kustrutten,www.rannikkoreitti.fi,None,None,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[276828.64...",275247.378348,6.684717e+06,0.010,23.809524
3,15,15.0,Virkistysreitti,Rekreationsrutt,Recreational route,Matkailureitti,Turistrutt,Tourist route,Raukkaan reitti,None,None,"Masku, Mynämäki, Naantali, Nousiainen, Raisio,...",Turun seutu,Varsinais-Suomi,Vanha kulttuurimatkailureitti keskisessä Varsi...,None,None,None,126100,None,None,None,None,None,None,ei ylläpitoa,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,0,23,02,F,None,None,False,notknown,False,0,NaN,617565,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617565,617565,Huvikummuntie,28840,Pori,609,Pori,"Polun muodostavat Promenadi, Rinki ja hieman e...",14,Pyöräilyreitti,Cykelled,Biking route,EuroVelo 10 - Yyteri/Pori - Turku,EuroVelo 10 - Yyteri/Pori - Turku,www.bikeland.fi,erkki@esimerkki.fi,+358401234567,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[221352.82...",220601.294985,6.731014e+06,0.192,25.000000
4,16,16.0,Virkistysreitti,Rekreationsrutt,Recreational route,Matkailureitti,Turistrutt,Tourist route,Hämeen Härkätie,None,None,"Kaarina, Koski Tl, Lieto, Marttila, Somero, Turku",None,Varsinais-Suomi,Vanha kauppatavaroiden kuljettamiseen perustet...,None,None,None,93600,None,https://www.harkatie.com/,None,None,None,None,ei tietoa ylläpitäjästä,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,"LN, kukkahammar",None,0,0,02,F,None,None,False,notknown,False,0,NaN,608867,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,608867,608867,Vanha Härkätie 111,21410,Vanhalinna,423,Lieto,Merkitään maastoon aikaisintaan 2023,3,Pyöräilyreitti,Cykelled,Biking route,Hämeen Härkätie (Lieto),Petrus väg,http://www.reitisto.fi/harkatie,erkki@esimerkki.fi,+358401234567,Muu,Muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[255237.89...",255149.615188,6.718437e+06,0.114,78.947368

In [48]:
summed_df = summed_df[~summed_df["gid"].isin(low_overlap_gids)]
summed_df.shape

(212, 75)

In [49]:
matched_routes = pd.concat([matched_routes, best_low_overlap_rows], ignore_index=True)
matched_routes

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio,fuzz_score
0,11,11.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Loukinaisten kuntorata,None,None,Lieto,Turun seutu,Varsinais-Suomi,"2,1 km pitkä valaistu kuntorata. Talvisin kunt...",None,None,None,2200,None,http://www.lieto.fi/,None,None,None,None,Liedon kunta,None,ei tietoa ylläpitoluokasta,None,None,None,2022/11/14,tuomohy,None,423,23,02,F,None,None,False,notknown,False,515096.0,NaN,515096,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,515096,515096,Airikintie,21410,Vanhalinna,423,Lieto,Talvikaudella kävely ja ulkoilu. Ei latua.,7,Kuntorata,Konditionsbana,Jogging track,Loukinaisten valaistu ulkoilurata,None,http://www.lieto.fi/,None,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[247163.76...",247188.208809,6.713565e+06,1.059,NaN
1,20,20.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Pöytyän Riihikosken urheilupuiston kuntorata,Riihikoski i Pöytis motionsbana,Pöytyä Riihikoski fitness trail,Pöytyä,Loimaan seutu,Varsinais-Suomi,Valaistu 1 km kuntorata. Maapohjan omistaa Pöy...,Upplyst 1 km motionsbana,1 km fitness trail with public lightning.,None,1000,None,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,https://www.poytya.fi/vapaa-aika-ja-matkailu/l...,None,None,Pöytyän kunta,None,ei tietoa ylläpitoluokasta,None,None,None,2023/08/22,LN,None,636,25,02,F,None,None,False,notknown,False,95745.0,NaN,95745,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,95745,95745,Yläneentie 14,21870,Riihikoski,636,Pöytyä,None,1,Kuntorata,Konditionsbana,Jogging track,Riihikosken kuntorata,None,None,None,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[259734.77...",259577.326500,6.739808e+06,1.000,NaN
2,23,23.0,Virkistysreitti,Rekreationsrutt,Recreational route,Melontareitti,Paddlingsrutt,Canoeing route,Mynäjoen melontareitti,Virmo å paddlingsrutt,Mynäjoki paddling route,Mynämäki,Turun seutu,Varsinais-Suomi,Maakuntakaavan suunniteltu melontareitti,En planerad paddlingsrutt i landskapsplanen,A planned paddlings route in the regional land...,None,39500,None,None,None,None,None,None,ei tietoa ylläpitäjästä,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,503,23,02,F,None,None,False,notknown,False,97077.0,NaN,97077,4451,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,97077,97077,Mynäjoentie,23100,Mynämäki,503,Mynämäki,None,2,Melontareitti,Paddlingsled,Canoe route,Mynäjoen melontareitti,None,None,None,+358401234567,Ei tietoa,Ei tietoa,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[222512.84...",221524.143730,6.732327e+06,1.001,NaN
3,26,26.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Nunnavuoren kuntorata,None,None,Turku,Turun seutu,Varsinais-Suomi,"1,7 km pitkä valaistu kuntoreitti. Talvella la...",None,None,None,2100,None,https://www.turku.fi/kulttuuri-ja-liikunta/lii...,None,None,None,None,Turun kaupunki,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,853,23,02,F,None,None,False,notknown,False,520340.0,NaN,520340,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,520340,520340,Kurrapolku 8,20320,Turku,853,Turku,None,1,Kuntorata,Konditionsbana,Jogging track,Nunnavuoren kuntorata,Nunnebergets motionsbana,http://www.turku.fi/vapaa-aika/liikunta/ulkoli...,erkki@esimerkki.fi,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[239318.28...",239600.849578,6.714672e+06,1.032,NaN
4,31,31.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Viitankruunun muinaispolku,None,None,Salo,Salon seutu,Varsinais-Suomi,Viitamäen luontopolun varrella on muinaisia ra...,None,None,None,500,None,http://www.salo.fi/attachements/2018-03-15T12-...,None,None,None,None,None,None,ei ylläpitoa,None,None,None,2021/01/01,"LN, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,601682.0,NaN,601682,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,601682,601682,Merikulmantie 259,24130,Salo,734,Salo,Viitankruunun muinaispolku lähtee Merikulmanti...,2,Luontopolku,Naturstig,Nature trail,Viitankruunun muinaispolku,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[284181,66...",284180.000000,6.697812e+06,1.017,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,302511,NaN,Virkistysreitti,rekreationsrutt,recreational route,Melontareitti,paddlingsrutt,paddling route,"Merikotkan kierros, etappi 2. Mathildedal - Ul...","Havsörnarnas rutt, etapp 2. Mathildedal - Utö ...","Sea Eagle Trail, stage 2. Mathildedal - Ulkol...","Kemiönsaari, Salo","Åboland-Turunmaa, Salo",Varsinais-Suomi,Etappi 2 vie sinut tutustumaan merellisen Salo...,Den andra etappen går genom den historiska Str...,Stage 2 of the Sea Eagle Trail takes you to th...,None,21550,None,https://out.ac/FtstO,None,None,None,None,None,None,ei tietoa ylläpitoluokasta,None,2022/12/21,None,2022/12/21,sannamari,None,"322, 734","021, 022",02,F,Johannes Sipponen / Visit Salo,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,0.0,NaN,510791,4451,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,510791,510791,Veitakkalantie,24260,Salo,734,Salo,Veneily- ja melontareitti,1,Melontareitti,Paddlingsled,Canoe route,Melontareitti Uskelanjoki-Särkisalo,Havsörnarnas rutt,https://out.ac/EAYUH,erkki@esimerkki.fi,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[289821.75...",278056.648826,6.687692e+06,0.101,34.090909
424,302513,NaN,Virkistysreitti,rekreationsrutt,recreational route,Melontareitti,paddlingsrutt,paddling route,"Merikotkan kierros, etappi 3. Ulkoluoto - Taal...","Havsörnarnas rutt, etapp 3. Utö (Salo) - Dalsbruk","Sea Eagle Trail, stage 3. Ulkoluoto - Dalsbruk","Raasepori, Kemiönsaari, Salo","Raasepori, Åboland-Turunmaa, Salo","Uusimaa, Varsinais-Suomi",Matkalla Ulkoluodolta Taalintehtaan ruukkikylä...,Färden från Utö till Dalsbruks bruksby går för...,On the way from Ulkoluoto to Dalsbruk ironwork...,None,26010,None,https://out.ac/Ftsxx,None,None,None,None,None,None,ei tietoa ylläpitoluokasta,None,2022/12/21,None,2022/12/21,sannamari,None,"710, 322, 734","014, 021, 022","01, 02",F,Visit Kimitoön,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,0.0,NaN,606212,4452,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,606212,606212,Vretanie 19,25800,None,322,Kemiönsaari,Veneily- ja melontareitti,1,Vesiretkeilyreitti,Utflyktsled i vattendrag,Water route,Merikotkan kierros,Havsörnarnas rutt,https://out.ac/EAYUH,None,None,Muu,Muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[278029.12...",257394.665423,6.671769e+06,0.009,50.000000
425,302591,NaN,Virkistysreitti,rekreationsrutt,recreational route,Pyöräilyreitti,cyklingsrutt,biking route,Rannikkoreitti: meriosuus Rosala - Bengtskär -...,Kustrutten: havsetappen Rosala - Bengtskär - ...,Coastal Route: Sea Stage Rosala - Bengtskär -...,"Hanko, Kemiönsaari","Raasepori, Åboland-Turunmaa","Uusimaa, Varsinais-Suomi",Kasnäsin ja Hangon merietappi tarjoaa pyöräili...,Havsetappen mellan Kasnäs och Hangö bjuder cyk...,The sea stage between Kasnäs and Hanko offers ...,None,0,None,https://www.bikeland.fi/rannikkoreitti,None,None,None,None,None,None,ei tietoa ylläpitoluokasta,None,2023/01/17,None,2023/01/17,sannamari,None,"078, 322","014, 021","01, 02",F,Visit Kimitoön,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,0.0,NaN,604266,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,604266,604266,Engelsbyntie 8,25700,None,322,Kemiönsaari,None,29,Pyöräilyreitti,Cykelled,Biking route,Rannikkoreitti,Kustrutten,www.rannikkoreitti.fi,None,None,Kunta,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[273699.66...",288476.730179,6.644992e+06,0.001,42.424242
426,305856,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Pyhän Henrikin tie,None,None,"Turku, Rusko, Nousiainen, Pöytyä, Säkylä, Koke...",Turku,"Varsinais-Suomi, Satakunta",Pyhän Henrikin tien vaellusreitin kokonaispitu...,None,None,None,140000,None,https://www.henrikinvaellus.fi/pyhan-herikin-t...,None,None,None,None,None,None,ei tietoa ylläpitoluokasta,None,2024/08/06,None,2024/08/07,makilainematias,Pyhiinvaellus,"853, 704, 538, 636, 783, 271",023,02,F,None,None,False,notknown,False,0.0,NaN,617573,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617573,617573,Yläneentie,23100,Mynämäki,503,Mynämäki,Paavonpolut on merkitty sinisillä merkeillä. M...,1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Pyhän Henrikin tie (Mynämäki),Helenas väg,https://www.henrikinvaellus.fi/pyhan-herikin-t...,erkki@esimerkki.fi,+358401234567,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[241731.24...",235460.144501,6.743544e+06,0.078,76.595745
427,305994,NaN,Virkistysreitti,rekreationsrutt,recreational route,Pyöräilyreitti,cyklingsrutt,biking route,Pyhän Henrikin pyöräilyreitti,None,None,"Turku, Rusko, Nousiainen, Pöytyä, Säkylä, Kok...","Turku, Loimaa",Varsinais-Suomi,Pyhän Henrikin tien vaellusreitin kokonaispitu...,None,None,None,140000,None,https://www.henrikinvaellus.fi/pyhan-herikin-t...,None,None,erkki@esimerkki.fi,None,Pyhän Henrikin Pyhiinvaellusyhdistys ry.,erkki@esimerkki.fi,ajoittainen,None,2025/02/05,None,2025/02/05,NR,None,503,023,02,T,None,None,False,notknown,False,0.0,NaN,617573,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617573,617573,Yläneentie,23100,Mynämäki,503,Mynämäki,"Perusreitti 22 km, perusreitti + Korventaustan...",1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Pyhän Henrikin tie (Mynämäki),Helenas väg,https://www.henrikinvaellus.fi/pyhan-herikin-t...,erkki@esimerkki.fi,+358401234567,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[241731.24...",235460.144501,6.743544e+06,0.143,58.620690

In [50]:
summed_df["overlap_ratio"].value_counts()

overlap_ratio
0.000    34
0.002    14
0.001    12
0.005     6
0.011     5
         ..
0.027     1
0.081     1
0.110     1
0.224     1
0.134     1
Name: count, Length: 114, dtype: int64

In [51]:
summed_df.loc[
    (summed_df["fuzz_score"] > 70),
    ["gid", "name_fi", "nimi_fi", "class2_fi", "tyyppi_nimi_fi", "overlap_ratio", "municipali", "kunta_nimi_fi", "fuzz_score"]
]

,gid,name_fi,nimi_fi,class2_fi,tyyppi_nimi_fi,overlap_ratio,municipali,kunta_nimi_fi,fuzz_score
86,19,Aurajoen melontareitti,Aurajoen melontareitti,Melontareitti,Melontareitti,0.448,"Aura, Kaarina, Lieto, Pöytyä, Turku",Turku,100.000000
89,19,Aurajoen melontareitti,Aurajoen melontareitti (Lieto),Melontareitti,Melontareitti,0.242,"Aura, Kaarina, Lieto, Pöytyä, Turku",Lieto,84.615385
330,118,Paattisten luontopolku,Paattisten jokipolku,Luontopolku,Retkeilyreitti,0.011,Turku,Turku,80.952381
331,118,Paattisten luontopolku,Paattisten luontopolku,Luontopolku,Luontopolku,0.352,Turku,Turku,100.000000
379,136,Koivumäen muinaispolku,Koivumäen muinaispolku,Luontopolku,Luontopolku,0.294,Salo,Salo,100.000000
545,266,Biskopsön luontopolku,Biskopsön luontopolku,Luontopolku,Luontopolku,0.296,Kemiönsaari,Kemiönsaari,100.000000
594,301,Asemanseudun luontopolku,Asemanseudun luontopolku,Retkeilyreitti,Retkeilyreitti,0.495,Mynämäki,Mynämäki,100.000000
614,312,Tuorlan luontopolku,Tuorlan esteetön luontopolku,Luontopolku,Luontopolku,0.272,Kaarina,Kaarina,80.851064
690,368,Vargbergetin polku,Vargbergetin reitti,Luontopolku,Retkeilyreitti,0.312,Parainen,Parainen,70.270270
802,436,Auranlaakson koulumetsän opetuspolku,Auranlaakson luontopolku,Luontopolku,Luontopolku,0.318,Kaarina,Kaarina,73.333333
848,445,Kuusiston-Harvaluodon melontareitti,Kuusiston-Harvaluodon melontareitti,Melontareitti,Melontareitti,0.298,Kaarina,Kaarina,100.000000
872,302272,Vuosnaisten luontopolku,Vuosnaisten luontopolku,Luontopolku,Luontopolku,0.493,Kustavi,Kustavi,100.000000
1171,305745,Oinilan jokipolku,Oinilan jokipolku,Retkeilyreitti,Luontopolku,0.482,Paimio,Paimio,100.000000

In [52]:
summed_df.shape

(212, 75)

In [53]:
summed_df = summed_df.reset_index(drop=True)
matched_routes = matched_routes.reset_index(drop=True)

In [54]:
summed_df.loc[
    (summed_df["fuzz_score"] > 80)
    & (summed_df['tyyppi_nimi_fi'] == summed_df['class2_fi'].map(mapping_dict))
].shape

(9, 75)

In [55]:
summed_df.loc[
    (summed_df["fuzz_score"] > 80)
    & (summed_df['tyyppi_nimi_fi'] == summed_df['class2_fi'].map(mapping_dict)),
    "lipas_id"
] = summed_df["id_2"]

In [56]:
summed_df = summed_df[
    (~summed_df['gid'].isin(summed_df.loc[summed_df['lipas_id'].notna() & (summed_df['lipas_id'] != 0), 'gid']))
    | ((summed_df['lipas_id'].notna()) & (summed_df['lipas_id'] != 0))
].copy()

summed_df.shape

(188, 75)

In [57]:
new_rows = summed_df.loc[
    (summed_df['lipas_id'].notna()) & (summed_df['lipas_id'] != 0)
].copy()


matched_routes = pd.concat([matched_routes, new_rows], ignore_index=True)

In [58]:
summed_df = summed_df.drop(new_rows.index)
summed_df.shape

(179, 75)

In [59]:
matched_routes.shape

(437, 75)

In [60]:
summed_df = summed_df.reset_index(drop=True)
matched_routes = matched_routes.reset_index(drop=True)

In [61]:
summed_df.loc[
    (summed_df["overlap_ratio"] > 0.2),
    ["gid", "name_fi", "nimi_fi", "class2_fi", "tyyppi_nimi_fi", "overlap_ratio", "municipali", "kunta_nimi_fi", "fuzz_score"]
]

,gid,name_fi,nimi_fi,class2_fi,tyyppi_nimi_fi,overlap_ratio,municipali,kunta_nimi_fi,fuzz_score
0,13,Kuhankuonon retkeilyreitistö - Hauninen-Ruissa...,Vaskipolku,Retkeilyreitti,Retkeilyreitti,0.205,"Raisio, Turku",Raisio,11.904762
3,13,Kuhankuonon retkeilyreitistö - Hauninen-Ruissa...,Kuntorata Pansiontie-Härkämäki,Retkeilyreitti,Kuntorata,0.291,"Raisio, Turku",Turku,25.000000
20,14,Kuninkaantie,EuroVelo 10 - Itämeren reitti,Matkailureitti,Pyöräilyreitti,0.262,"Kaarina, Paimio, Salo, Turku",Tornio,24.390244
21,14,Kuninkaantie,EuroVelo 10 - Turku-Helsinki,Matkailureitti,Pyöräilyreitti,0.272,"Kaarina, Paimio, Salo, Turku",Naantali,25.000000
24,17,Paavonpolut: Yhdysreitti: Halinen-Oriketo,Kuntorata Halinen-Oriketo,Kuntoreitti,Kuntorata,0.311,Turku,Turku,60.606061
26,17,Paavonpolut: Yhdysreitti: Halinen-Oriketo,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.368,Turku,Turku,42.307692
28,17,Paavonpolut: Yhdysreitti: Halinen-Oriketo,Halinen-Oriketo latu,Kuntoreitti,Hiihtolatu,0.286,Turku,Turku,59.016393
46,22,Pohjanlahden rantatie,EuroVelo 10 - Itämeren reitti,Matkailureitti,Pyöräilyreitti,0.341,"Laitila, Pyhäranta, Uusikaupunki, Vehmaa",Tornio,36.000000
50,38,Kuhankuonon retkeilyreitistö - Karevan kierto,Rivieran ulkoilureitti,Retkeilyreitti,Kävelyreitti/ulkoilureitti,0.201,"Masku, Raisio, Rusko",Masku,41.791045
55,63,Pyhän Olavin merireitti - Nauvon kirkonkylä-I...,Mittilandsvägen,Retkeilyreitti,Retkeilyreitti,0.329,Parainen,Parainen,16.279070
59,88,Littoistenjärven pohjoinen polkuyhteys (epävir...,Kuuden kunnanosan kierros,Kulttuuriulkoilureitti,Pyöräilyreitti,0.249,Lieto,Lieto,25.581395
63,133,Kaupunkitarinoita Turusta,EuroVelo 10 - Itämeren reitti,Kulttuuriulkoilureitti,Pyöräilyreitti,0.305,Turku,Tornio,25.925926
64,133,Kaupunkitarinoita Turusta,EuroVelo 10 - Turku-Helsinki,Kulttuuriulkoilureitti,Pyöräilyreitti,0.321,Turku,Naantali,33.962264
65,133,Kaupunkitarinoita Turusta,EuroVelo 10 - Yyteri/Pori - Turku,Kulttuuriulkoilureitti,Pyöräilyreitti,0.313,Turku,Pori,31.034483
70,139,Porrastelu- porrastele kukkuloille (reitti A),Pyhää kohti - keskiaikainen pyhiinvaellusreitt...,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,0.212,Turku,Turku,32.000000
75,143,Porrastelu- porrastele kukkuloille (reitti C),EuroVelo 10 - Turku-Helsinki,Kulttuuriulkoilureitti,Pyöräilyreitti,0.213,Turku,Naantali,30.136986
76,143,Porrastelu- porrastele kukkuloille (reitti C),EuroVelo 10 - Yyteri/Pori - Turku,Kulttuuriulkoilureitti,Pyöräilyreitti,0.201,Turku,Pori,30.769231
80,171,I love Halinen -kulttuuriulkoilureitti (reitti 2),Pietarin polku,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,0.219,Turku,Turku,25.396825
84,180,Kurittulan kuntorata,Rydön rinki,Kuntoreitti,Kuntorata,0.292,Loimaa,Loimaa,25.806452
85,215,Marjaniemen polku,Ruissalon luontopolut,Luontopolku,Luontopolku,0.385,Turku,Turku,36.842105
86,287,Piiloleikki - etsi kätketyt pikkupatsaat,EuroVelo 10 - Itämeren reitti,Kulttuuriulkoilureitti,Pyöräilyreitti,0.449,Turku,Tornio,34.782609
87,287,Piiloleikki - etsi kätketyt pikkupatsaat,EuroVelo 10 - Turku-Helsinki,Kulttuuriulkoilureitti,Pyöräilyreitti,0.488,Turku,Naantali,29.411765
88,287,Piiloleikki - etsi kätketyt pikkupatsaat,EuroVelo 10 - Yyteri/Pori - Turku,Kulttuuriulkoilureitti,Pyöräilyreitti,0.468,Turku,Pori,24.657534
94,288,Patsastelu - reitti 3: Yliopiston alue,Pyhää kohti - keskiaikainen pyhiinvaellusreitt...,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,0.291,Turku,Turku,45.161290
97,297,Hiunjärven luontopolku,Hiunjärven ulkoilureitti,Luontopolku,Luontopolku,0.484,Uusikaupunki,Uusikaupunki,65.217391
104,305,Suomen Sydän - aikamatka historiaan,Pietarin polku,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,0.479,Turku,Turku,24.489796
109,352,Paavonpolut (reitti 10D): Hirvensalo: Majamäki...,Paavonpolut,Kuntoreitti,Retkeilyreitti,0.471,Turku,Turku,33.846154
113,360,Kerttula-Petäsmäki -yhdysreitti,Kerttulan ja Petäsmäen yhdyslatu,Kuntoreitti,Hiihtolatu,1.068,Raisio,Raisio,47.619048
114,366,Tarvasjoen luontopolku,Hämeen Härkätie (Lieto),Luontopolku,Pyöräilyreitti,0.263,Lieto,Lieto,22.222222
115,368,Vargbergetin polku,Vargbergetin reitti,Luontopolku,Retkeilyreitti,0.312,Parainen,Parainen,70.270270
116,375,I love Halinen -kulttuuriulkoilureitti (reitti 1),Kuntorata Halinen-Oriketo,Kulttuuriulkoilureitti,Kuntorata,0.204,Turku,Turku,27.027027
119,375,I love Halinen -kulttuuriulkoilureitti (reitti 1),Pietarin polku,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,0.230,Turku,Turku,25.396825
123,436,Auranlaakson koulumetsän opetuspolku,Auranlaakson luontopolku,Luontopolku,Luontopolku,0.318,Kaarina,Kaarina,73.333333
125,442,Littoistenjärvi,Littoistenjärven melontareitti,Melontareitti,Melontareitti,0.296,"Lieto, Kaarina",Lieto,66.666667
126,302296,"Raukkaankosken rantapolku, kanoottien maihinno...",Mynäjoen melontareitti,Retkeilyreitti,Melontareitti,0.217,Mynämäki,Mynämäki,25.974026
127,302296,"Raukkaankosken rantapolku, kanoottien maihinno...",Asemanseudun luontopolku,Retkeilyreitti,Retkeilyreitti,0.407,Mynämäki,Mynämäki,37.974684
128,302308,Kipparin polku,Vuohensaaren luontopolku,Luontopolku,Luontopolku,0.268,Salo,Salo,47.368421
129,302486,Hiittinen & Rosala: Polje saaristolaiskyliin v...,Rannikkoreitti,Pyöräilyreitti,Pyöräilyreitti,0.312,Kemiönsaari,Kemiönsaari,17.948718
131,302486,Hiittinen & Rosala: Polje saaristolaiskyliin v...,Hiittinen ja Rosala pyöräillen,Pyöräilyreitti,Pyöräilyreitti,0.389,Kemiönsaari,Kemiönsaari,53.191489
132,302489,Kiilan latu,Kiilan kuntorata,Latu,Kuntorata,0.945,Kemiönsaari,Kemiönsaari,66.666667
133,302521,Kiilan latu,Kiilan kuntorata,Latu,Kuntorata,0.945,Kemiönsaari,Kemiönsaari,66.666667
136,302590,Rannikkoreitti: Taalintehdas - Rosala 25 km,Rannikkoreitti,Pyöräilyreitti,Pyöräilyreitti,0.487,Kemiönsaari,Kemiönsaari,49.122807
140,302590,Rannikkoreitti: Taalintehdas - Rosala 25 km,Hiittinen ja Rosala pyöräillen,Pyöräilyreitti,Pyöräilyreitti,0.218,Kemiönsaari,Kemiönsaari,43.835616
142,305745,Oinilan jokipolku,Oinilan jokipolku,Retkeilyreitti,Luontopolku,0.482,Paimio,Paimio,100.000000
172,305913,Jaakontie pyhiinvaellusreitti,Hämeen Härkätie pyöräilyreitti,Kulttuuriulkoilureitti,Pyöräilyreitti,0.224,Raisio,Hämeenlinna,50.847458

In [62]:
summed_df["gid"].value_counts()

gid
305913    36
22        17
14        15
305       11
17         9
288        8
133        8
13         8
302590     8
375        7
171        7
139        5
38         4
88         4
143        4
360        4
63         3
302486     3
287        3
302296     2
436        2
297        1
180        1
215        1
442        1
368        1
352        1
366        1
302489     1
302308     1
302521     1
305745     1
Name: count, dtype: int64

In [63]:
names_to_update = ["Oinilan jokipolku", "Littoistenjärvi"]

mask = summed_df["name_fi"].isin(names_to_update)
summed_df.loc[mask, "lipas_id"] = summed_df.loc[mask, "id_2"]

In [64]:
summed_df.shape

(179, 75)

In [65]:
matched_routes.shape

(437, 75)

In [66]:
updated_rows = summed_df.loc[mask].copy()
gids_to_remove = updated_rows["gid"].unique()
summed_df = summed_df[~summed_df["gid"].isin(gids_to_remove)]

In [67]:
matched_routes = pd.concat([matched_routes, updated_rows], ignore_index=True)
matched_routes.shape

(439, 75)

In [68]:
deduped = (
    summed_df.sort_values(["gid", "overlap_ratio"], ascending=[True, False])
    .drop_duplicates(subset="gid", keep="first")
    .copy()
)

# 2️⃣ Set lipas_id = 0 for these
deduped["lipas_id"] = 0

# 3️⃣ Append to matched_routes
matched_routes = pd.concat([matched_routes, deduped], ignore_index=True)

In [69]:
matched_routes.shape

(469, 75)

In [70]:
summed_df = summed_df[~summed_df["gid"].isin(deduped["gid"])]

In [71]:
df2 = pd.read_csv("routes_db.csv")
df2.head()

,gid,geom,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked
0,305557,MULTILINESTRING ((247585.75070000027 6736508.0...,NaN,Virkistysreitti,rekreationsrutt,recreational route,Retkeilyreitti,vandringsrutt,hiking route,Vajosuon kierros,NaN,NaN,Rusko,Turku,Varsinais-Suomi,Kuvaus,NaN,NaN,NaN,1120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ei tietoa ylläpitoluokasta,NaN,2023-08-02,NaN,2023-08-02,"laurale, NR",NaN,704,023,02,F,NaN,NaN,False,notknown,False,NaN,NaN
1,302297,"MULTILINESTRING ((222788 6734427, 222820 67344...",NaN,Virkistysreitti,rekreationsrutt,recreational route,Retkeilyreitti,vandringsrutt,hiking route,Tammimetsä,NaN,NaN,Mynämäki,Turku,Varsinais-Suomi,Saa poiketa merkityltä polulta,NaN,NaN,NaN,270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ajoittainen,NaN,2022-05-17,NaN,2023-06-20,Karimakela,NaN,503,023,02,F,NaN,NaN,False,notknown,False,NaN,NaN
2,274,MULTILINESTRING ((298169.9422854949 6731386.22...,274.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Jogging track,Pitkäjärven kuntorata ja latu,NaN,NaN,Somero,Salon seutu,Varsinais-Suomi,Pitkäjärven kuntoradan päällyste on hiekkaa. V...,NaN,NaN,NaN,2800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ei tietoa ylläpitoluokasta,NaN,NaN,NaN,2021-01-01,"LN, JanitaKylanpaa",NaN,761,22,02,F,NaN,NaN,False,notknown,False,NaN,NaN
3,184,MULTILINESTRING ((285129.750004753 6701206.749...,184.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Nakolinnan luontopolku,Nakolinna naturstig,Nakolinna nature trail,Salo,Salon seutu,Varsinais-Suomi,"Pituus 1,2 km. Reitti merkitty matalilla jouts...","Ruttens längd 1,2 km. Rutten är markerad med s...","Length of the route is 1,2 km. The route is ma...",NaN,1200,NaN,https://kohteet.visitsalo.fi/nakolinnan-luonto...,https://kohteet.visitsalo.fi/nakolinnan-luonto...,https://kohteet.visitsalo.fi/nakolinnan-luonto...,erkki@esimerkki.fi,NaN,Salon kaupunki,erkki@esimerkki.fi,ei tietoa ylläpitoluokasta,NaN,NaN,NaN,2022-06-23,"LN, TerhiSalosta, SaloMK",NaN,734,22,02,F,NaN,NaN,False,notknown,False,NaN,NaN
4,302365,MULTILINESTRING ((217981.83349999978 6732415.9...,NaN,Virkistysreitti,rekreationsrutt,recreational route,Retkeilyreitti,vandringsrutt,hiking route,Silakkarin maisemakallion reitti,NaN,NaN,Turku,Turku,Varsinais-Suomi,Metsähallituksen ylläpitämä kesäretkeilyreitti,NaN,NaN,NaN,2270,NaN,https://www.sll.fi/mynamaenseutu/paikallisluon...,NaN,NaN,NaN,NaN,NaN,NaN,ei tietoa ylläpitoluokasta,NaN,2022-11-18,NaN,2024-03-20,NR,NaN,853,023,02,F,NaN,NaN,False,notknown,False,NaN,NaN

In [72]:
df2.loc[~df2["gid"].isin(matched_routes["gid"])]

,gid,geom,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked
0,305557,MULTILINESTRING ((247585.75070000027 6736508.0...,NaN,Virkistysreitti,rekreationsrutt,recreational route,Retkeilyreitti,vandringsrutt,hiking route,Vajosuon kierros,NaN,NaN,Rusko,Turku,Varsinais-Suomi,Kuvaus,NaN,NaN,NaN,1120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ei tietoa ylläpitoluokasta,NaN,2023-08-02,NaN,2023-08-02,"laurale, NR",NaN,704,023,02,F,NaN,NaN,False,notknown,False,NaN,NaN
4,302365,MULTILINESTRING ((217981.83349999978 6732415.9...,NaN,Virkistysreitti,rekreationsrutt,recreational route,Retkeilyreitti,vandringsrutt,hiking route,Silakkarin maisemakallion reitti,NaN,NaN,Turku,Turku,Varsinais-Suomi,Metsähallituksen ylläpitämä kesäretkeilyreitti,NaN,NaN,NaN,2270,NaN,https://www.sll.fi/mynamaenseutu/paikallisluon...,NaN,NaN,NaN,NaN,NaN,NaN,ei tietoa ylläpitoluokasta,NaN,2022-11-18,NaN,2024-03-20,NR,NaN,853,023,02,F,NaN,NaN,False,notknown,False,NaN,NaN
14,90,MULTILINESTRING ((249979.61149999965 6742648.8...,90.0,Virkistysreitti,Rekreationsrutt,Recreational route,Retkeilyreitti,Vandringsled,Hiking trail,Rihtniemen lintutornille johtava polku,NaN,NaN,Pyhäranta,Vakka-Suomi,Varsinais-Suomi,Lintutornille johtava reitti. Maapohja on valt...,NaN,NaN,NaN,100,NaN,http://www.rslh.info/index.php?option=com_cont...,NaN,NaN,NaN,NaN,Metsähallitus,NaN,ajoittainen,NaN,NaN,NaN,2021-01-01,laurale,NaN,631,24,02,F,NaN,NaN,False,notknown,False,NaN,NaN
15,137,MULTILINESTRING ((279841.99220580567 6684858.7...,137.0,Virkistysreitti,Rekreationsrutt,Recreational route,Retkeilyreitti,Vandringsled,Hiking trail,Postinummen polku (osa Sahajärven kierrosta),NaN,NaN,Salo,Salon seutu,Varsinais-Suomi,Sahajärven kierros kokonaisuutena on 8 km. Alu...,NaN,NaN,NaN,1200,NaN,http://www.luontoon.fi/teijo/reitit,NaN,NaN,NaN,NaN,Metsähallitus,NaN,ajoittainen,NaN,NaN,NaN,2021-01-01,"laurale, TerhiSalosta, SaloMK",Teijo,734,22,02,F,NaN,NaN,False,notknown,False,NaN,NaN
17,129,MULTILINESTRING ((244886.74260000026 6756328.0...,129.0,Virkistysreitti,Rekreationsrutt,Recreational route,Retkeilyreitti,Vandringsled,Hiking trail,Kuhankuonon retkeilyreitistö - Vaskijärven reitti,Kuhankuono vandringsledar - Vaskijärvi rutt,Kuhankuono hiking trails - Vaskijärvi Route,Pöytyä,Loimaan seutu,Varsinais-Suomi,Oranssi nauha + 3 sinistä palloa = ymypyräreit...,"Orange band + 3 blå bollar = cirkulär bana, or...","Orange ribbon + 3 blue balls = circular path, ...",NaN,19300,NaN,https://kuhankuono.fi/reitit/vaskijarven-reitti/,https://www.utinaturen.fi/kurjenrahka/vaskijar...,https://www.nationalparks.fi/kurjenrahkanp/vas...,NaN,NaN,Metsähallitus,NaN,ajoittainen,NaN,NaN,NaN,2023-08-02,laurale,NaN,636,25,02,F,NaN,NaN,False,notknown,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,324,"MULTILINESTRING ((258860 6722946, 258857 67229...",324.0,Virkistysreitti,rekreationsrutt,recreational route,Luontopolku,naturstig,nature trail,Tornivuoren näkötornin polku,NaN,NaN,Lieto,Turku,Varsinais-Suomi,Noin 150 metrin mittainen polku Tornivuoren p-...,NaN,NaN,keskivaikea,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ei tietoa ylläpitoluokasta,"Reitti selkeä maastossa, mutta sitä ei ole mer...",NaN,NaN,2022-03-30,LN,NaN,423,023,02,F,NaN,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,NaN,NaN
546,6,"MULTILINESTRING ((277253.9668 6683681.0187, 27...",6.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Rannikkoreitti,NaN,NaN,Salo,NaN,NaN,www.rannikkoreitti.fi,NaN,NaN,NaN,5090,NaN,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,NaN,NaN,NaN,NaN,Kunta / muu,NaN,ei tietoa ylläpitoluokasta,NaN,NaN,NaN,2021-01-02,"AKos, TerhiSalosta, SaloMK",NaN,734,22,02,F,NaN,NaN,False,notknown,False,NaN,NaN
551,365,MULTILINESTRING ((225818.61773217464 6728256.1...,365.0,Virkistysreitti,Rekreationsrutt,Recreational route,Retkeilyreitti,Vandringsled,Hiking trail,Kolkanpolku - Kuuvanvuoren reitti,Kolkanpolku - Kuuvanvuori stigen,Kolkanpolku - Kuuvanvuori path,Masku,Turun seutu,Varsinais-Suomi,Kuuvanvuoren reitti on yksi kolmesta Kolkanpol...,Kuuvanvuori stigen är en av tre del rutter av ...,Kuuvanvuori path is a part of the three subrou...,NaN,2200,NaN,http://www.masku.fi/tyo-ja-yrittaminen/matkail...,NaN,NaN,NaN,NaN,Partiolippukunta Kolkan Kävijät,NaN,ei tietoa ylläpitoluokasta,hyvä,NaN,NaN,2022-03-30,"LN, TA, jutani",Leader-kohde,481,23,02,F,NaN,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,NaN,NaN
563,364,MULTILINESTRING ((244159.91363630912 6690154.6...,364.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Mustikkapolku,Blåbärstigen,Blueberry path,Parainen,Turunmaa,Varsinais-Suomi,"2,8 km pitkä polku. Merkitty sinisillä merkinn...","2,8 km rutt. Blå markeringar. Terrängen är ber...","2,8 km lång trail marked with blue signs. The ...","keskitasoa - korkeuseroja on, mutta ei kovin j...",2900,"Reitillä on jonkin verran korkeuseroa, joten h...",https://www.pargas.fi/fi/luontopolut-ja-retkei...,https://www.pargas.fi/sv/web/pargas/naturstiga...,https://www.pargas.fi/documents/41921/0/Bl%C3%...,NaN,NaN,Paraisten kaupunki,NaN,ei tietoa ylläpitoluokasta,Reitti on hyvin merkitty maastoon sinisillä vi...,NaN,NaN,2022-03-30,LN,NaN,445,21,02,F,NaN,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,NaN,NaN
564,316,MULTILINESTRING ((193359.99104890786 6780319.3...,316.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Hierkonpolku,NaN,NaN,Pyhäranta,Vakka-Suomi,Varsinais-Suomi,Hierkonpolku on rantapolku Reilan entisen soti...,NaN,NaN,NaN,2300,NaN,https://reidu.yhdistysavain.fi/hierkonpolku/,NaN,NaN,NaN,NaN,Reilan kyläyhdistys REIDU ry,NaN,ajoittainen,"Rakenteet ja opasteet hyvässä kunnossa, reitti...",NaN,NaN,2022-03-30,"LN, TA",Leader-hanke,631,24,02,F,NaN,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,NaN,NaN

In [73]:
df["gid"].nunique()

449

In [74]:
matched_routes["gid"].nunique()

449

In [75]:
df2["gid"].nunique()

566

In [76]:
matched_routes.loc[
    matched_routes.duplicated(subset="gid", keep=False),
    ["name_fi", "nimi_fi", "overlap_ratio", "class2_fi", "tyyppi_nimi_fi", "gid"]
].sort_values("gid")

,name_fi,nimi_fi,overlap_ratio,class2_fi,tyyppi_nimi_fi,gid
429,Aurajoen melontareitti,Aurajoen melontareitti (Lieto),0.242,Melontareitti,Melontareitti,19
428,Aurajoen melontareitti,Aurajoen melontareitti,0.448,Melontareitti,Melontareitti,19
23,Hirvikosken kuntorata,Hirvikosken pururata,1.078,Kuntoreitti,Kuntorata,159
24,Hirvikosken kuntorata,Loimaan Perhekierros Hirvikoskella,0.018,Kuntoreitti,Pyöräilyreitti,159
320,Koroistenniemen polku,Helenan polku,0.917,Luontopolku,Kävelyreitti/ulkoilureitti,221
319,Koroistenniemen polku,Pietarin polku,0.857,Luontopolku,Kävelyreitti/ulkoilureitti,221
160,Masuunilammen luontopolku,Senatsberget hyvinvointipolku,0.542,Luontopolku,Luontopolku,257
159,Masuunilammen luontopolku,Masuunilammen luontopolku,0.984,Luontopolku,Luontopolku,257
165,Laitilan Matikan kuntorata,Matikan kuntorata,0.952,Kuntoreitti,Kuntorata,278
166,Laitilan Matikan kuntorata,Matikan 5km hiihtolatu,0.872,Kuntoreitti,Kuntorata,278
176,Rannikkoreitti - Hiittinen ja Rosala,Hiittinen ja Rosala pyöräillen,0.630,Pyöräilyreitti,Pyöräilyreitti,320
175,Rannikkoreitti - Hiittinen ja Rosala,Rannikkoreitti,0.594,Pyöräilyreitti,Pyöräilyreitti,320
204,Kaarina-Paimio pyöräilyn yhdysreitti,EuroVelo 10 - Itämeren reitti,0.553,Pyöräilyreitti,Pyöräilyreitti,444
205,Kaarina-Paimio pyöräilyn yhdysreitti,EuroVelo 10 - Turku-Helsinki,0.572,Pyöräilyreitti,Pyöräilyreitti,444
111,Rauhalinnan luontopolku helppokulkuinen,Rauhalinnan luontopolku,1.050,Luontopolku,Luontopolku,472
112,Rauhalinnan luontopolku helppokulkuinen,Rauhalinnan luontopolku helppokulkuinen,1.021,Luontopolku,Luontopolku,472
212,Kasnäsin ulkoilureitti 3 km,Kasnäsin ulkoilureitit,0.578,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302465
213,Kasnäsin ulkoilureitti 3 km,"Kasnäsin ulkoilureitti, esteetön reitti",0.846,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302465
221,Kulttuuripolkaisu Dragsfjärdenin järven ympäri,Rannikkoreitti,0.543,Pyöräilyreitti,Pyöräilyreitti,302483
222,Kulttuuripolkaisu Dragsfjärdenin järven ympäri,Kulttuuripolkaisu Dragsfjärden järven ympäri,0.701,Pyöräilyreitti,Pyöräilyreitti,302483
231,Kasnäsin ulkoilureitti 3 km,Kasnäsin ulkoilureitit,0.578,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302497
232,Kasnäsin ulkoilureitti 3 km,"Kasnäsin ulkoilureitti, esteetön reitti",0.846,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302497
239,Kulttuuripolkaisu Dragsfjärdenin järven ympäri,Rannikkoreitti,0.543,Pyöräilyreitti,Pyöräilyreitti,302515
240,Kulttuuripolkaisu Dragsfjärdenin järven ympäri,Kulttuuripolkaisu Dragsfjärden järven ympäri,0.701,Pyöräilyreitti,Pyöräilyreitti,302515
249,Kasnäsin ulkoilureitti 3 km,Kasnäsin ulkoilureitit,0.578,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302529
250,Kasnäsin ulkoilureitti 3 km,"Kasnäsin ulkoilureitti, esteetön reitti",0.846,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302529
255,Kasnäsin ulkoilureitti 3 km,Kasnäsin ulkoilureitit,0.578,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302535
256,Kasnäsin ulkoilureitti 3 km,"Kasnäsin ulkoilureitti, esteetön reitti",0.846,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302535
260,Kasnäsin ulkoilureitti 3 km,Kasnäsin ulkoilureitit,0.578,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302540
261,Kasnäsin ulkoilureitti 3 km,"Kasnäsin ulkoilureitti, esteetön reitti",0.846,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302540
262,Kasnäsin ulkoilureitti 3 km,Kasnäsin ulkoilureitit,0.578,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302542
263,Kasnäsin ulkoilureitti 3 km,"Kasnäsin ulkoilureitti, esteetön reitti",0.846,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302542
265,Kasnäsin ulkoilureitti 3 km,"Kasnäsin ulkoilureitti, esteetön reitti",0.846,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302544
264,Kasnäsin ulkoilureitti 3 km,Kasnäsin ulkoilureitit,0.578,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302544
267,Kasnäsin ulkoilureitti 3 km,"Kasnäsin ulkoilureitti, esteetön reitti",0.846,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302546
266,Kasnäsin ulkoilureitti 3 km,Kasnäsin ulkoilureitit,0.578,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302546
269,Kasnäsin ulkoilureitti 3 km,"Kasnäsin ulkoilureitti, esteetön reitti",0.846,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302548
268,Kasnäsin ulkoilureitti 3 km,Kasnäsin ulkoilureitit,0.578,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,302548
276,Rannikkoreitti: Tammisaari - Tenhola 18 km,EuroVelo 10 - Turku-Helsinki,0.750,Pyöräilyreitti,Pyöräilyreitti,302592
275,Rannikkoreitti: Tammisaari - Tenhola 18 km,Rannikkoreitti,0.773,Pyöräilyreitti,Pyöräilyreitti,302592

In [77]:
matched_routes[matched_routes["lipas_id"] == 0]

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio,fuzz_score
339,1,1.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Kuusiston linnanraunioiden pyöräilyreitti,None,None,Kaarina,Turun seutu,Varsinais-Suomi,Reitti on yhteen suuntaan 6 km ja edestakaisin...,None,None,None,590,None,http://www.reitisto.fi/kuusistonpyorailyreitti,None,None,erkki@esimerkki.fi,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,0.0,NaN,606780,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,606780,606780,Linnanrauniontie 556,21620,Kaarina,202,Kaarina,Reitti on yhteen suuntaan 6 km ja edestakaisin...,1,Pyöräilyreitti,Cykelled,Biking route,Kuusiston linnanraunioiden pyöräilyreitti,None,http://www.reitisto.fi/kuusistonpyorailyreitti,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246350.08...",248425.143461,6.703885e+06,0.019,100.000000
340,4,4.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Rannikkoreitti,None,None,Salo,None,None,www.rannikkoreitti.fi,None,None,None,4910,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,None,None,None,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,0.0,NaN,616807,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,616807,616807,Pakkahuoneenkatu,95400,Tornio,851,Tornio,None,1,Pyöräilyreitti,Cykelled,Biking route,EuroVelo 10 - Itämeren reitti,EuroVelo 10 - Baltic Sea Cycle Route,www.rannikkoreitti.fi,None,None,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[369864.68...",317309.074686,6.905632e+06,0.082,32.558140
341,5,5.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Rannikkoreitti,None,None,Salo,None,None,www.rannikkoreitti.fi,None,None,None,2700,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,None,None,None,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,0.0,NaN,617406,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617406,617406,Tullikatu 9,21100,Naantali,529,Naantali,None,2,Pyöräilyreitti,Cykelled,Biking route,EuroVelo 10 - Turku-Helsinki,Kustrutten,www.rannikkoreitti.fi,None,None,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[276828.64...",275247.378348,6.684717e+06,0.010,23.809524
342,15,15.0,Virkistysreitti,Rekreationsrutt,Recreational route,Matkailureitti,Turistrutt,Tourist route,Raukkaan reitti,None,None,"Masku, Mynämäki, Naantali, Nousiainen, Raisio,...",Turun seutu,Varsinais-Suomi,Vanha kulttuurimatkailureitti keskisessä Varsi...,None,None,None,126100,None,None,None,None,None,None,ei ylläpitoa,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,LN,None,0,23,02,F,None,None,False,notknown,False,0.0,NaN,617565,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617565,617565,Huvikummuntie,28840,Pori,609,Pori,"Polun muodostavat Promenadi, Rinki ja hieman e...",14,Pyöräilyreitti,Cykelled,Biking route,EuroVelo 10 - Yyteri/Pori - Turku,EuroVelo 10 - Yyteri/Pori - Turku,www.bikeland.fi,erkki@esimerkki.fi,+358401234567,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[221352.82...",220601.294985,6.731014e+06,0.192,25.000000
343,16,16.0,Virkistysreitti,Rekreationsrutt,Recreational route,Matkailureitti,Turistrutt,Tourist route,Hämeen Härkätie,None,None,"Kaarina, Koski Tl, Lieto, Marttila, Somero, Turku",None,Varsinais-Suomi,Vanha kauppatavaroiden kuljettamiseen perustet...,None,None,None,93600,None,https://www.harkatie.com/,None,None,None,None,ei tietoa ylläpitäjästä,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,"LN, kukkahammar",None,0,0,02,F,None,None,False,notknown,False,0.0,NaN,608867,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,608867,608867,Vanha Härkätie 111,21410,Vanhalinna,423,Lieto,Merkitään maastoon aikaisintaan 2023,3,Pyöräilyreitti,Cykelled,Biking route,Hämeen Härkätie (Lieto),Petrus väg,http://www.reitisto.fi/harkatie,erkki@esimerkki.fi,+358401234567,Muu,Muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[255237.89...",255149.615188,6.718437e+06,0.114,78.947368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,302486,NaN,Virkistysreitti,rekreationsrutt,recreational route,Pyöräilyreitti,cyklingsrutt,biking route,Hiittinen & Rosala: Polje saaristolaiskyliin v...,Hitis & Rosala: Cykla till skärgårdsbyarna i v...,Hitis & Rosala Islands: Cycle to the archipela...,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,Tee pyörällä saarihyppely Rosalan ja Hiittiste...,Hoppa på cykeln och öluffa ut till skärgårdsö...,Jump on your bike and island hop out to the ar...,None,20000,None,https://www.visitkimitoon.fi/fi/nae-ja-koe/akt...,None,None,None,None,None,None,ei ylläpitoa,None,2022/12/21,None,2022/12/21,sannamari,None,322,021,02,F,Jasmin Yuchun / Visit Kimitoön,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,0.0,NaN,610792,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,610792,610792,Kasnäs,25930,None,322,Kemiönsaari,Reittiehdotus; ei merkitty maastoon,1,Pyöräilyreitti,Cykelled,Biking route,Hiittinen ja Rosala pyöräillen,Hitis och Rosala med cykel,None,None,None,Kunta,Muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[249665.39...",248010.774559,6.646861e+06,0.389,53.191489
465,302489,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Kiilan latu,Kila skidspår,Kila ski track,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,Valaistu latu. Katso ajantasainen latutilanne:...,Upplyst spår. Se den aktuella spårsituationen:...,See the up-to-date track situation: latutilann...,None,1100,None,None,None,None,None,None,None,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,0.0,NaN,95946,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,95946,95946,Mainiementie,25760,Kiila,322,Kemiönsaari,"Lenkin pituus 1,5 km.",1,Kuntorata,Konditionsbana,Jogging track,Kiilan kuntorata,Kila motionsbana,http://kemionsaari.fi/fi/nae_koe/urheilu_liiku...,None,None,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[271735.70...",271790.436404,6.684073e+06,0.945,66.666667
466,302521,NaN,Virkistysreitti,rekreationsrutt,recreational route,Latu,vandringsskidspår,trekking ski track,Kiilan latu,Kila skidspår,Kila ski track,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,Valaistu latu. Katso ajantasainen latutilanne:...,Upplyst spår. Se den aktuella spårsituationen:...,See the up-to-date track situation: latutilann...,None,1100,None,None,None,None,None,None,None,None,ajoittainen,None,2022/12/20,None,2022/12/20,sannamari,None,322,021,02,F,None,None,False,notknown,False,0.0,NaN,95946,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,95946,95946,Mainiementie,25760,Kiila,322,Kemiönsaari,"Lenkin pituus 1,5 km.",1,Kuntorata,Konditionsbana,Jogging track,Kiilan kuntorata,Kila motionsbana,http://kemionsaari.fi/fi/nae_koe/urheilu_liiku...,None,None,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[271735.70...",271790.436404,6.684073e+06,0.945,66.666667
467,302590,NaN,Virkistysreitti,rekreationsrutt,recreational route,Pyöräilyreitti,cyklingsrutt,biking route,Rannikkoreitti: Taalintehdas - Rosala 25 km,Kustrutten: Dalsbruk - Kasnäs 25 km,Coastal Route: Dalsbruk - Kasnäs 25 km,Kemiönsaari,Åboland-Turunmaa,Varsinais-Suomi,Tämä etappi tarjoaa merimaisemia pyörän seläst...,Denna etapp erbjuder havsvyer från cykelsadeln...,This leg of the journey offers sea views from ...,None,25000,None,https://www.bikeland.fi/rannikkoreitti,None,None,None,None,None,None,ei tietoa ylläpitoluokasta,None,2023/01/17,None,2023/01/17,sannamari,None,322,021,02,F,Sanna-Mari Kunttu / Visit Kimitoön,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,0.0,NaN,604266,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,604266,604266,Engelsbyntie 8,25700,None,322,Kemiönsaari,None,39,Pyöräilyreitti,Cykelled,Biking route,Rannikkoreitti,Kustrutten,www.rannikkoreitti.fi,None,None,Kunta,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[264609.44...",254803.828095,6.671355e+06,0.487,49.122807
468,305913,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Jaakontie pyhiinvaellusreitti,None,None,Raisio,Turku,Varsinais-Suomi,Hämeen Härkätie on Santiago de Compostelaan jo...,None,None,None,242400,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,None,None,erkki@esimerkki.fi,None,Jakontie ystävät ry,https://jaakontienystavat.wordpress.com/,ei tietoa ylläpitoluokasta,None,2024/09/12,None,2024/09/17,NR,Pyhiinvaellus,680,023,02,T,None,None,False,notknown,False,0.0,NaN,615622,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,615622,615622,Kustaa III:n katu,13100,Hämeenlinna,109,Hämeenlinna,The Oxroad of Häme trail is suitable for more ...,1,Pyöräilyreitti,Cykelled,Biking route,Hämeen Härkätie pyöräilyreitti,None,None,None,None,Muu,Muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[321093.18...",343732.638967,6.749872e+06,0.224,50.847458

In [78]:
mask = (matched_routes["name_fi"] == "Rauhalinnan luontopolku helppokulkuinen") & (matched_routes["nimi_fi"] == "Rauhalinnan luontopolku")
matched_routes = matched_routes[~mask]

In [79]:
# sort so highest overlap_ratio appears first per gid
matched_routes = matched_routes.sort_values(["gid", "overlap_ratio"], ascending=[True, False])

# keep only highest-overlap row per gid
matched_routes = matched_routes.drop_duplicates(subset="gid", keep="first")

In [80]:
matched_routes.loc[matched_routes["name_fi"] == "Koroistenniemen polku", "lipas_id"] = 0

In [81]:
matched_routes.loc[matched_routes["name_fi"] == "Kaarina-Paimio pyöräilyn yhdysreitti", "lipas_id"] = 0

In [82]:
matched_routes.loc[matched_routes["name_fi"] == "Kuusiston linnanraunioiden pyöräilyreitti"]

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio,fuzz_score
339,1,1.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Kuusiston linnanraunioiden pyöräilyreitti,None,None,Kaarina,Turun seutu,Varsinais-Suomi,Reitti on yhteen suuntaan 6 km ja edestakaisin...,None,None,None,590,None,http://www.reitisto.fi/kuusistonpyorailyreitti,None,None,erkki@esimerkki.fi,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,0.0,NaN,606780,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,606780,606780,Linnanrauniontie 556,21620,Kaarina,202,Kaarina,Reitti on yhteen suuntaan 6 km ja edestakaisin...,1,Pyöräilyreitti,Cykelled,Biking route,Kuusiston linnanraunioiden pyöräilyreitti,None,http://www.reitisto.fi/kuusistonpyorailyreitti,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246350.08...",248425.143461,6.703885e+06,0.019,100.0
196,415,415.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Kuusiston linnanraunioiden pyöräilyreitti,None,None,Kaarina,Turun seutu,Varsinais-Suomi,"Reitti on melko tasainen, välillä loivasti ku...",None,None,None,6300,None,http://www.reitisto.fi/kuusistonpyorailyreitti,http://www.reitisto.fi/kuusistonpyorailyreitti,http://www.reitisto.fi/kuusistonpyorailyreitti,None,None,"Kaarinan ja Paimion kaupungit, sekä Liedon ja ...",None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/01,"tuomohy, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,606780.0,NaN,606780,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,606780,606780,Linnanrauniontie 556,21620,Kaarina,202,Kaarina,Reitti on yhteen suuntaan 6 km ja edestakaisin...,1,Pyöräilyreitti,Cykelled,Biking route,Kuusiston linnanraunioiden pyöräilyreitti,None,http://www.reitisto.fi/kuusistonpyorailyreitti,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246350.08...",248425.143461,6.703885e+06,0.788,NaN

In [83]:
matched_routes.loc[
    matched_routes["lipas_id"] == 0,
    ["gid", "name_fi", "nimi_fi", "overlap_ratio", "class2_fi", "tyyppi_nimi_fi", "timestamp", "lipas_id"]
].iloc[0:50]

,gid,name_fi,nimi_fi,overlap_ratio,class2_fi,tyyppi_nimi_fi,timestamp,lipas_id
339,1,Kuusiston linnanraunioiden pyöräilyreitti,Kuusiston linnanraunioiden pyöräilyreitti,0.019,Pyöräilyreitti,Pyöräilyreitti,2021/01/02,0.0
340,4,Rannikkoreitti,EuroVelo 10 - Itämeren reitti,0.082,Pyöräilyreitti,Pyöräilyreitti,2021/01/02,0.0
341,5,Rannikkoreitti,EuroVelo 10 - Turku-Helsinki,0.010,Pyöräilyreitti,Pyöräilyreitti,2021/01/02,0.0
439,13,Kuhankuonon retkeilyreitistö - Hauninen-Ruissa...,Kuntorata Pansiontie-Härkämäki,0.291,Retkeilyreitti,Kuntorata,2021/01/01,0.0
440,14,Kuninkaantie,EuroVelo 10 - Turku-Helsinki,0.272,Matkailureitti,Pyöräilyreitti,2021/01/01,0.0
342,15,Raukkaan reitti,EuroVelo 10 - Yyteri/Pori - Turku,0.192,Matkailureitti,Pyöräilyreitti,2021/01/01,0.0
343,16,Hämeen Härkätie,Hämeen Härkätie (Lieto),0.114,Matkailureitti,Pyöräilyreitti,2021/01/01,0.0
441,17,Paavonpolut: Yhdysreitti: Halinen-Oriketo,Paavonpolut,0.368,Kuntoreitti,Retkeilyreitti,2021/01/01,0.0
344,21,Velhoveden kierros - pääreitti,EuroVelo 10 - Yyteri/Pori - Turku,0.068,Pyöräilyreitti,Pyöräilyreitti,2021/01/01,0.0
442,22,Pohjanlahden rantatie,EuroVelo 10 - Itämeren reitti,0.341,Matkailureitti,Pyöräilyreitti,2021/01/01,0.0
345,25,Paattisten Jokipolku,Paattisten jokipolku,0.159,Luontopolku,Retkeilyreitti,2021/01/01,0.0
346,34,Vestlaxin luontopolku,Rannikkoreitti,0.016,Luontopolku,Pyöräilyreitti,2021/01/01,0.0
347,37,Kuhankuonon retkeilyreitistö - Kangemiekka-Reh...,Pyhän Henrikin tie (Rusko),0.004,Retkeilyreitti,Kävelyreitti/ulkoilureitti,2021/01/01,0.0
443,38,Kuhankuonon retkeilyreitistö - Karevan kierto,Rivieran ulkoilureitti,0.201,Retkeilyreitti,Kävelyreitti/ulkoilureitti,2022/08/15,0.0
348,43,Turku on... - kohtaa kaupunki uusin silmin.,Luomakunnan huokaus meissä - kaupunki pyhiinva...,0.094,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,2021/01/01,0.0
349,49,Romanttinen Turku - retki rakkaustarinoihin,EuroVelo 10 - Turku-Helsinki,0.178,Kulttuuriulkoilureitti,Pyöräilyreitti,2021/01/01,0.0
350,57,Suuri Postitie,EuroVelo 10 - Yyteri/Pori - Turku,0.154,Matkailureitti,Pyöräilyreitti,2021/01/01,0.0
351,60,Sauvo-Kemiönsaari pyöräilyn yhdysreitti,Sauvon kierros,0.006,Pyöräilyreitti,Pyöräilyreitti,2022/03/22,0.0
352,61,Sauvon melontareitti,Sauvon melontareitti,0.165,Melontareitti,Melontareitti,2022/03/22,0.0
353,62,Lausteen luontopolku,Kaarinan perintömetsän luontopolku,0.140,Luontopolku,Luontopolku,2021/01/01,0.0
444,63,Pyhän Olavin merireitti - Nauvon kirkonkylä-I...,Mittilandsvägen,0.329,Retkeilyreitti,Retkeilyreitti,2021/01/01,0.0
354,67,Kuusiston linnanraunioiden luontopolku,Kuusiston linnanraunioiden pyöräilyreitti,0.036,Luontopolku,Pyöräilyreitti,2021/01/01,0.0
445,88,Littoistenjärven pohjoinen polkuyhteys (epävir...,Kuuden kunnanosan kierros,0.249,Kulttuuriulkoilureitti,Pyöräilyreitti,2021/01/01,0.0
355,89,Littoistenjärven itärannan ulkoilureittiura,Kuuden kunnanosan kierros,0.171,Kulttuuriulkoilureitti,Pyöräilyreitti,2021/01/01,0.0
356,109,Kuusisto-Harvaluoto-Paimionjoki melonnan yhdys...,Melonnan yhdysreitti Kaarina-Paimio,0.086,Melontareitti,Melontareitti,2021/01/01,0.0
357,119,Metsämaan kuntorata,Metsämaan pururata,0.071,Kuntoreitti,Kuntorata,2021/01/01,0.0
358,127,Ihmeellinen Turku - sattumia ja saloja,Henrikin polku,0.151,Kulttuuriulkoilureitti,Pyöräilyreitti,2021/01/01,0.0
359,131,Patsastelu - reitti 2: Samppalinnanpuisto - It...,Urheilupuiston kuntorata - Karikon lenkki,0.106,Kulttuuriulkoilureitti,Kuntorata,2021/01/01,0.0
446,133,Kaupunkitarinoita Turusta,EuroVelo 10 - Turku-Helsinki,0.321,Kulttuuriulkoilureitti,Pyöräilyreitti,2021/01/01,0.0
360,134,"Lost in Turku - etsi, katoa ja löydä",EuroVelo 10 - Turku-Helsinki,0.029,Kulttuuriulkoilureitti,Pyöräilyreitti,2021/01/01,0.0
361,135,Paavonpolut: Yhdysreitti: Varissuo-Lauste,Kaarinan perintömetsän luontopolku,0.069,Kuntoreitti,Luontopolku,2021/01/01,0.0
447,139,Porrastelu- porrastele kukkuloille (reitti A),Pyhää kohti - keskiaikainen pyhiinvaellusreitt...,0.212,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,2021/01/01,0.0
362,140,Jeturkastin muinaispolku - esteetön osuus,Rannikkoreitti,0.034,Retkeilyreitti,Pyöräilyreitti,2021/01/01,0.0
448,143,Porrastelu- porrastele kukkuloille (reitti C),EuroVelo 10 - Turku-Helsinki,0.213,Kulttuuriulkoilureitti,Pyöräilyreitti,2021/01/01,0.0
363,156,Kuusiston Kappelinmäen luontopolku,Kuusiston linnanraunioiden pyöräilyreitti,0.130,Luontopolku,Pyöräilyreitti,2022/08/11,0.0
364,160,Saariston rengastie - pieni rengastie,EuroVelo 10 - Itämeren reitti,0.081,Pyöräilyreitti,Pyöräilyreitti,2023/03/10,0.0
365,161,Saariston rengastie - suuri rengastie,EuroVelo 10 - Itämeren reitti,0.092,Matkailureitti,Pyöräilyreitti,2022/03/30,0.0
366,170,I love Halinen -kulttuuriulkoilureitti (reitti 3),Pietarin polku,0.109,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,2021/01/01,0.0
449,171,I love Halinen -kulttuuriulkoilureitti (reitti 2),Pietarin polku,0.219,Kulttuuriulkoilureitti,Kävelyreitti/ulkoilureitti,2022/01/26,0.0
450,180,Kurittulan kuntorata,Rydön rinki,0.292,Kuntoreitti,Kuntorata,2023/07/18,0.0
367,187,Enäjärvi-Särkisalo -melontareitti,EuroVelo 10 - Itämeren reitti,0.001,Melontareitti,Pyöräilyreitti,2021/01/01,0.0
451,215,Marjaniemen polku,Ruissalon luontopolut,0.385,Luontopolku,Luontopolku,2021/01/01,0.0
368,218,Kansanpuiston lenkki,Ruissalon luontopolut,0.154,Luontopolku,Luontopolku,2021/01/01,0.0
320,221,Koroistenniemen polku,Helenan polku,0.917,Luontopolku,Kävelyreitti/ulkoilureitti,2021/01/01,0.0
369,223,Jeturkastin muinaispolku,Rannikkoreitti,0.010,Retkeilyreitti,Pyöräilyreitti,2021/01/01,0.0
370,225,Matildajärven kierros,EuroVelo 10 - Itämeren reitti,0.087,Retkeilyreitti,Pyöräilyreitti,2022/08/11,0.0
371,227,Onnelannummen reitti,Rannikkoreitti,0.003,Retkeilyreitti,Pyöräilyreitti,2021/01/01,0.0
372,239,Kultaranta Resortin Kuru-ulkoilureitistö: Kall...,EuroVelo 10 - Yyteri/Pori - Turku,0.145,Retkeilyreitti,Pyöräilyreitti,2021/01/01,0.0
373,260,Myllyrannan luontopolku,Paimiojoen melontareitti,0.013,Luontopolku,Melontareitti,2022/03/30,0.0
374,261,Halikonjoen melontareitti,Melontareitti Uskelanjoki-Särkisalo,0.011,Melontareitti,Melontareitti,2021/01/01,0.0

In [84]:
matched_routes[matched_routes["lipas_id"] != 0].shape

(328, 75)

In [85]:
matched_routes.loc[matched_routes["name_fi"] == "Vähäjokipolku", "lipas_id"] = 605010

In [86]:
matched_routes.loc[matched_routes["name_fi"] == "Paavonpolut: Yhdysreitti: Runosmäki-Impivaara", "lipas_id"] = 525507

In [87]:
matched_routes.loc[matched_routes["name_fi"] == "Paavonpolut: Yhdysreitti: Lauste-Skanssi", "lipas_id"] = 525507

In [88]:
matched_routes.loc[matched_routes["name_fi"] == "Aurajoentien matkailutie", "lipas_id"] = 0

In [89]:
matched_routes.loc[matched_routes["name_fi"] == "Vanha Tampereentie pyöräilyn yhdysreitti", "lipas_id"] = 0

In [90]:
matched_routes.loc[matched_routes["name_fi"] == "Suontaan latu", "lipas_id"] = 524366

In [91]:
matched_routes.loc[matched_routes["gid"] == 1, "lipas_id"] = 606780

In [99]:
matched_routes.loc[matched_routes["name_fi"] == "Tuorlan luontopolku", "lipas_id"] = 0

In [100]:
matched_routes.loc[matched_routes["name_fi"] == "Oinilan maauimalan kuntorata", "lipas_id"] = 0

In [106]:
matched_routes.loc[matched_routes["name_fi"] == "Torpparin taival", "lipas_id"] = 0

In [107]:
matched_routes.loc[matched_routes["name_fi"] == "Kreivin kierros", "lipas_id"] = 0

In [108]:
matched_routes.loc[matched_routes["name_fi"] == "Raision Jokiraitti", "lipas_id"] = 0

In [109]:
matched_routes.loc[matched_routes["name_fi"] == "Tarvasjoen Tarvashovin kuntorata", "lipas_id"] = 0

In [110]:
matched_routes.loc[matched_routes["name_fi"] == "Kaarinan Pyhän Katariinan polut", "lipas_id"] = 0

In [111]:
matched_routes[matched_routes["lipas_id"] != 0]

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio,fuzz_score
339,1,1.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Kuusiston linnanraunioiden pyöräilyreitti,None,None,Kaarina,Turun seutu,Varsinais-Suomi,Reitti on yhteen suuntaan 6 km ja edestakaisin...,None,None,None,590,None,http://www.reitisto.fi/kuusistonpyorailyreitti,None,None,erkki@esimerkki.fi,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,606780.0,NaN,606780,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,606780,606780,Linnanrauniontie 556,21620,Kaarina,202,Kaarina,Reitti on yhteen suuntaan 6 km ja edestakaisin...,1,Pyöräilyreitti,Cykelled,Biking route,Kuusiston linnanraunioiden pyöräilyreitti,None,http://www.reitisto.fi/kuusistonpyorailyreitti,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246350.08...",248425.143461,6.703885e+06,0.019,100.000000
281,3,3.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Kuusiston koulupolku,None,None,Kaarina,Turun seutu,Varsinais-Suomi,None,None,None,None,1260,None,http://www.reitisto.fi/kuusistonkoulupolku,None,None,erkki@esimerkki.fi,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,605796.0,NaN,605796,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,605796,605796,Pallotie 2 / Kuusiston koulutie 14,21620,Kuusisto,202,Kaarina,None,1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Kuusiston koulupolku,None,http://www.reitisto.fi/kuusistonkoulupolku,erkki@esimerkki.fi,None,Muu,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246664.09...",246216.536538,6.703447e+06,1.000,100.000000
298,7,7.0,Virkistysreitti,Rekreationsrutt,Recreational route,Retkeilyreitti,Vandringsled,Hiking trail,tuntematon 5,None,None,None,None,None,None,None,None,None,8100,None,None,None,None,None,None,None,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,None,None,None,None,None,F,None,None,True,notknown,False,603101.0,NaN,603101,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,603101,603101,Talviniityntie 116,21420,Lieto,423,Lieto,None,1,Luontopolku,Naturstig,Nature trail,Ankka-Nautela luontopolku,None,http://www.reitisto.fi/ankka-nautela,None,None,Muu,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[252295.82...",252392.110766,6.718453e+06,1.001,32.432432
0,11,11.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Loukinaisten kuntorata,None,None,Lieto,Turun seutu,Varsinais-Suomi,"2,1 km pitkä valaistu kuntorata. Talvisin kunt...",None,None,None,2200,None,http://www.lieto.fi/,None,None,None,None,Liedon kunta,None,ei tietoa ylläpitoluokasta,None,None,None,2022/11/14,tuomohy,None,423,23,02,F,None,None,False,notknown,False,515096.0,NaN,515096,4401,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,515096,515096,Airikintie,21410,Vanhalinna,423,Lieto,Talvikaudella kävely ja ulkoilu. Ei latua.,7,Kuntorata,Konditionsbana,Jogging track,Loukinaisten valaistu ulkoilurata,None,http://www.lieto.fi/,None,+358401234567,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[247163.76...",247188.208809,6.713565e+06,1.059,NaN
117,12,12.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,naturstig,nature trail,Ankka-Nautela luontopolku,None,None,Lieto,Turun seutu,Varsinais-Suomi,Ankka-Nautela luontopolku alkaa Liedon kirkonk...,None,None,None,7200,None,http://www.reitisto.fi/ankka-nautela,None,None,None,None,Ankka-Nautela luontopolun ylläpidosta vastaa L...,None,ajoittainen,None,None,None,2021/09/07,tuomohy,None,423,23,02,F,None,None,False,notknown,False,603101.0,NaN,603101,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,603101,603101,Talviniityntie 116,21420,Lieto,423,Lieto,None,2,Luontopolku,Naturstig,Nature trail,Ankka-Nautela luontopolku,None,http://www.reitisto.fi/ankka-nautela,None,None,Muu,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[252812.53...",252049.757097,6.720674e+06,0.554,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,305745,NaN,Virkistysreitti,rekreationsrutt,recreational route,Retkeilyreitti,vandringsrutt,hiking route,Oinilan jokipolku,None,None,Paimio,Turku,Varsinais-Suomi,2 km mittainen luontopolku Paimionjoen maisemi...,None,None,Polku on osittain mäkistä maastoa. Ei talvikun...,2030,None,https://paimionjoki.fi/luontokohde/paimion-luo...,None,None,None,None,Paimionjoki-yhdistys,www.paimionjoki.fi,ajoittainen,None,2023/12/18,None,2023/12/18,Paimionjokiyhd,None,577,023,02,T,None,None,False,notknown,False,605011.0,NaN,605011,4404,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,605011,605011,Sähköyhtiöntie 4,21530,Paimio,577,Paimio,None,1,Luontopolku,Naturstig,Nature trail,Oinilan jokipolku,None,None,None,None,Kunta,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[262578.89...",262686.290893,6.711728e+06,0.482,100.000000
279,305911,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Pietarin polku,None,None,Turku,Turku,Varsinais-Suomi,Pyhiinvaellusreitti,None,None,None,3510,None,None,None,None,None,None,None,None,ei tietoa ylläpitoluokasta,None,2024/09/12,None,2024/09/12,NR,None,853,023,02,F,None,None,False,notknown,False,617619.0,NaN,617619,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617619,617619,Hämeenkatu 13,20500,Turku,853,Turku,"Tällä pienellä pyhiinvaelluksella (2,4 km) kul...",1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Luomakunnan huokaus meissä - kaupunki pyhiinva...,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,erkki@esimerkki.fi,+358401234567,Muu,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240353.64...",240367.502382,6.711501e+06,0.990,NaN
280,305916,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Luomakunnan huokaus meissä,None,None,Turku,Turku,Varsinais-Suomi,Kaupunkipyhiinvaellus. Tällä pienellä pyhiinva...,None,None,None,210,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,None,None,erkki@esimerkki.fi,None,None,None,ei tietoa ylläpitoluokasta,None,2024/09/17,None,2024/09/20,NR,Pyhiinvaellus,284,025,02,F,None,https://pyhiinvaellussuomi.fi/wp-content/uploa...,False,notknown,False,617619.0,NaN,617619,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617619,617619,Hämeenkatu 13,20500,Turku,853,Turku,"Tällä pienellä pyhiinvaelluksella (2,4 km) kul...",1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Luomakunnan huokaus meissä - kaupunki pyhiinva...,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,erkki@esimerkki.fi,+358401234567,Muu,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240353.64...",240367.502382,6.711501e+06,0.990,NaN
116,305918,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Aurajoen pyhiinvaelluspolut - Helenan polku,None,None,Turku,Turku,Varsinais-Suomi,Noin 8 km pituinen Helenan polku sopii kuljett...,None,None,None,220,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,None,None,erkki@esimerkki.fi,None,None,None,ei tietoa ylläpitoluokasta,None,2024/09/17,None,2024/09/17,NR,Pyhiinvaellus,853,023,02,F,None,https://citynomadi.com/api/media/caTD6s9Q_lM8vd,False,notknown,False,612929.0,NaN,612929,4403,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,612929,612929,Hämeenkatu 13,20500,Turku,853,Turku,Noin 8 km pituinen Helenan polku sopii kuljett...,1,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Helenan polku,Helenas väg,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,erkki@esimerkki.fi,+358401234567,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240345.85...",241055.483622,6.712309e+06,1.000,NaN
297,305937,NaN,Virkistysreitti,rekreationsrutt,recreational route,Kulttuuriulkoilureitti,kulturfriluftsrutt,cultural outdoor route,Henrikin polku,None,None,Turku,Turku,Varsinais-Suomi,Henrikin polku on kaupungissa ja puistoalueill...,None,None,None,15000,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,None,None,None,None,None,None,jatkuva,None,2024/10/28,None,2024/10/28,NR,Pyhiinvaellus,853,023,02,F,None,None,False,notknown,False,617617.0,NaN,617617,4412,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617617,617617,Hämeenkatu 13,20500,Turku,853,Turku,Henrikin polku on kaupungissa ja puistoalueill...,1,Pyöräilyreitti,Cykelled,Biking route,Henrikin polku,None,https://pyhiinvaellussuomi.fi/pyhiinvaellus-re...,erkki@esimerkki.fi,+358401234567,Muu,Kunta / muu,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[240338.19...",240069.825604,6.708775e+06,0.980,100.000000

In [112]:
only_in_a = df2[~df2["gid"].isin(matched_routes["gid"])].copy()

In [113]:
only_in_a["lipas_id"] = 0

In [115]:
matched_routes = pd.concat([matched_routes, only_in_a], ignore_index=True)

In [116]:
matched_routes

,gid,id,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,length_m,accessibil,www_fi,www_se,www_en,email,telephone,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,timestamp,updater_id,special,munici_nro,subreg_nro,region_nro,publicinfo,picture,www_picture,hidden,datasource,ski_route,lipas_id,lipas_checked,id_2,tyyppikoodi,tyyppikoodi_alaryhma,tyyppikoodi_paaryhma,sijainti_id,reitisto_id,katuosoite,postinumero,postitoimipaikka,kuntanumero,kunta_nimi_fi,lisatieto_fi,reitti_id,tyyppi_nimi_fi,tyyppi_nimi_se,tyyppi_nimi_en,nimi_fi,nimi_se,www,sahkoposti,puhelinnumero,omistaja,yllapitaja,reitti_nimi_fi,reitti_nimi_se,reittiosa_json,x,y,overlap_ratio,fuzz_score,geom
0,1,1.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Kuusiston linnanraunioiden pyöräilyreitti,None,None,Kaarina,Turun seutu,Varsinais-Suomi,Reitti on yhteen suuntaan 6 km ja edestakaisin...,None,None,None,590,None,http://www.reitisto.fi/kuusistonpyorailyreitti,None,None,erkki@esimerkki.fi,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,606780.0,NaN,606780.0,4412.0,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,606780.0,606780.0,Linnanrauniontie 556,21620.0,Kaarina,202.0,Kaarina,Reitti on yhteen suuntaan 6 km ja edestakaisin...,1.0,Pyöräilyreitti,Cykelled,Biking route,Kuusiston linnanraunioiden pyöräilyreitti,None,http://www.reitisto.fi/kuusistonpyorailyreitti,erkki@esimerkki.fi,None,Kunta,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246350.08...",248425.143461,6.703885e+06,0.019,100.000000,NaN
1,3,3.0,Virkistysreitti,Rekreationsrutt,Recreational route,Kuntoreitti,Motionsbana,Fitness trail,Kuusiston koulupolku,None,None,Kaarina,Turun seutu,Varsinais-Suomi,None,None,None,None,1260,None,http://www.reitisto.fi/kuusistonkoulupolku,None,None,erkki@esimerkki.fi,None,Kunta / liikuntatoimi,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, kukkahammar",None,202,23,02,F,None,None,False,notknown,False,605796.0,NaN,605796.0,4403.0,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,605796.0,605796.0,Pallotie 2 / Kuusiston koulutie 14,21620.0,Kuusisto,202.0,Kaarina,None,1.0,Kävelyreitti/ulkoilureitti,Promenadled/friluftsled,Walking route/outdoor route,Kuusiston koulupolku,None,http://www.reitisto.fi/kuusistonkoulupolku,erkki@esimerkki.fi,None,Muu,Kunta / liikuntatoimi,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[246664.09...",246216.536538,6.703447e+06,1.000,100.000000,NaN
2,4,4.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Rannikkoreitti,None,None,Salo,None,None,www.rannikkoreitti.fi,None,None,None,4910,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,None,None,None,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,0.0,NaN,616807.0,4412.0,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,616807.0,616807.0,Pakkahuoneenkatu,95400.0,Tornio,851.0,Tornio,None,1.0,Pyöräilyreitti,Cykelled,Biking route,EuroVelo 10 - Itämeren reitti,EuroVelo 10 - Baltic Sea Cycle Route,www.rannikkoreitti.fi,None,None,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[369864.68...",317309.074686,6.905632e+06,0.082,32.558140,NaN
3,5,5.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Rannikkoreitti,None,None,Salo,None,None,www.rannikkoreitti.fi,None,None,None,2700,None,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,None,None,None,None,Kunta / muu,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,"AKos, TerhiSalosta, SaloMK",None,734,22,02,F,None,None,False,notknown,False,0.0,NaN,617406.0,4412.0,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,617406.0,617406.0,Tullikatu 9,21100.0,Naantali,529.0,Naantali,None,2.0,Pyöräilyreitti,Cykelled,Biking route,EuroVelo 10 - Turku-Helsinki,Kustrutten,www.rannikkoreitti.fi,None,None,Rekisteröity yhdistys,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[276828.64...",275247.378348,6.684717e+06,0.010,23.809524,NaN
4,7,7.0,Virkistysreitti,Rekreationsrutt,Recreational route,Retkeilyreitti,Vandringsled,Hiking trail,tuntematon 5,None,None,None,None,None,None,None,None,None,8100,None,None,None,None,None,None,None,None,ei tietoa ylläpitoluokasta,None,None,None,2021/01/02,None,None,None,None,None,F,None,None,True,notknown,False,603101.0,NaN,603101.0,4404.0,Liikunta- ja ulkoilureitit,Maastoliikuntapaikat,603101.0,603101.0,Talviniityntie 116,21420.0,Lieto,423.0,Lieto,None,1.0,Luontopolku,Naturstig,Nature trail,Ankka-Nautela luontopolku,None,http://www.reitisto.fi/ankka-nautela,None,None,Muu,Rekisteröity yhdistys,NaN,NaN,"{""type"":""LineString"",""coordinates"":[[252295.82...",252392.110766,6.718453e+06,1.001,32.432432,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561,324,324.0,Virkistysreitti,rekreationsrutt,recreational route,Luontopolku,naturstig,nature trail,Tornivuoren näkötornin polku,NaN,NaN,Lieto,Turku,Varsinais-Suomi,Noin 150 metrin mittainen polku Tornivuoren p-...,NaN,NaN,keskivaikea,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ei tietoa ylläpitoluokasta,"Reitti selkeä maastossa, mutta sitä ei ole mer...",NaN,NaN,2022-03-30,LN,NaN,423,023,02,F,NaN,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTILINESTRING ((258860 6722946, 258857 67229..."
562,6,6.0,Virkistysreitti,Rekreationsrutt,Recreational route,Pyöräilyreitti,Cyklingsrutt,Cycling route,Rannikkoreitti,NaN,NaN,Salo,NaN,NaN,www.rannikkoreitti.fi,NaN,NaN,NaN,5090,NaN,https://salo.fi/vapaa-aika-ja-matkailu/liikunt...,NaN,NaN,NaN,NaN,Kunta / muu,NaN,ei tietoa ylläpitoluokasta,NaN,NaN,NaN,2021-01-02,"AKos, TerhiSalosta, SaloMK",NaN,734,22,02,F,NaN,NaN,False,notknown,False,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTILINESTRING ((277253.9668 6683681.0187, 27..."
563,365,365.0,Virkistysreitti,Rekreationsrutt,Recreational route,Retkeilyreitti,Vandringsled,Hiking trail,Kolkanpolku - Kuuvanvuoren reitti,Kolkanpolku - Kuuvanvuori stigen,Kolkanpolku - Kuuvanvuori path,Masku,Turun seutu,Varsinais-Suomi,Kuuvanvuoren reitti on yksi kolmesta Kolkanpol...,Kuuvanvuori stigen är en av tre del rutter av ...,Kuuvanvuori path is a part of the three subrou...,NaN,2200,NaN,http://www.masku.fi/tyo-ja-yrittaminen/matkail...,NaN,NaN,NaN,NaN,Partiolippukunta Kolkan Kävijät,NaN,ei tietoa ylläpitoluokasta,hyvä,NaN,NaN,2022-03-30,"LN, TA, jutani",Leader-kohde,481,23,02,F,NaN,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTILINESTRING ((225818.61773217464 6728256.1...
564,364,364.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Mustikkapolku,Blåbärstigen,Blueberry path,Parainen,Turunmaa,Varsinais-Suomi,"2,8 km pitkä polku. Merkitty sinisillä merkinn...","2,8 km rutt. Blå markeringar. Terrängen är ber...","2,8 km lång trail marked with blue signs. The ...","keskitasoa - korkeuseroja on, mutta ei kovin j...",2900,"Reitillä on jonkin verran korkeuseroa, joten h...",https://www.pargas.fi/fi/luontopolut-ja-retkei...,https://www.pargas.fi/sv/web/pargas/naturstiga...,https://www.pargas.fi/documents/41921/0/Bl%C3%...,NaN,NaN,Paraisten kaupunki,NaN,ei tietoa ylläpitoluokasta,Reitti on hyvin merkitty maastoon sinisillä vi...,NaN,NaN,2022-03-30,LN,NaN,445,21,02,F,NaN,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTILINESTRING ((244159.91363630912 6690154.6...
565,316,316.0,Virkistysreitti,Rekreationsrutt,Recreational route,Luontopolku,Naturstig,Nature trail,Hierkonpolku,NaN,NaN,Pyhäranta,Vakka-Suomi,Varsinais-Suomi,Hierkonpolku on rantapolku Reilan entisen soti...,NaN,NaN,NaN,2300,NaN,https://reidu.yhdistysavain.fi/hierkonpolku/,NaN,NaN,NaN,NaN,Reilan kyläyhdistys REIDU ry,NaN,ajoittainen,"Rakenteet ja opasteet hyvässä kunnossa, reitti...",NaN,NaN,2022-03-30,"LN, TA",Leader-hanke,631,24,02,F,NaN,https://virmafipictures.s3.eu-west-1.amazonaws...,False,notknown,False,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MULTILINESTRING ((193359.99104890786 6780319.3...

In [128]:
matched_routes["lipas_id"] = matched_routes["lipas_id"].astype("int")

In [129]:
matched_routes["lipas_id"].dtypes

dtype('int64')

In [130]:
matched_routes_to_virma = matched_routes[["gid", "lipas_id"]].copy()

In [131]:
matched_routes_to_virma

     gid  lipas_id
0      1    606780
1      3    605796
2      4         0
3      5         0
4      7    603101
..   ...       ...
561  324         0
562    6         0
563  365         0
564  364         0
565  316         0

[566 rows x 2 columns]

In [132]:
matched_routes_to_virma.to_csv("routes_matched_ids.csv", index=False)