In [77]:
import pandas as pd

In [78]:
df = pd.read_csv("../possible_bool_columns/points_202506181545.csv")

In [79]:
pd.set_option('display.max_columns', None)
df.head()

,id,geom,fid,gid,class1_fi,class1_se,class1_en,class2_fi,class2_se,class2_en,name_fi,name_se,name_en,address,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,accessibil,equipment,www_fi,www_se,www_en,telephone,email,ownerclass,owner,upkeeper,upkeepinfo,upkeepclas,shapeestim,sh_es_date,sh_es_pers,updater_id,x_eureffin,y_eureffin,timestamp,zip,munici_nro,subreg_nro,region_nro,special,no_address,publicinfo,picture,www_picture,hidden,datasource,lipas_id,lipas_checked
0,NaN,POINT (175648 6744192),NaN,306002,Virkistyskohde,rekreationsobjekt,recreational attraction,Luonto- tai lintutorni,natur- eller fågeltorn,nature or bird watching tower,testi20250604uusidb,NaN,NaN,NaN,Kustavi,Vakka-Suomi,Varsinais-Suomi,testi20250604uusidb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Muu yksityinen yhteisö,NaN,NaN,NaN,ei ylläpitoa,NaN,2025-06-04,NaN,lamkoi2,175648.000000,6.744192e+06,2025-06-04,NaN,304,24,2,NaN,F,F,NaN,NaN,True,notknown,NaN,NaN
1,974.0,POINT (238506.4915756498 6709897.27508255),1001.0,974,Matkailupalvelukohde,Objekt för turismfunktioner,Tourist attraction,Vierassatama,Gästhamn,Guest harbour,Turun vierasvenesatama,Åbo gästhamn,NaN,Läntinen rantakatu 57,Turku,Turun seutu,Varsinais-Suomi,Venepaikkoja 60 kpl. Ennakkoon varattavia paikkoja on rajoitetusti.,NaN,NaN,NaN,NaN,"septitankin tyhjennys, sähkö, vesi, wifi, jätehuolto, kierrätys, sauna, suihku, pyykkitupa, tankkaus",https://www.turunvierasvenesatama.fi/,https://www.turunvierasvenesatama.fi/?lang=sv,https://www.turunvierasvenesatama.fi/?lang=en,+358 (0) 400 536 613,erkki@esimerkki.fi,Yhteinen alue,NaN,Turun vierasvenesatama / Auraport Oy,"Vierasvenesatamaa ylläpitää Turun vierasvenesatama / Auraport Oy, osoite: Läntinen Rantakatu 57, 20100 Turku, +358401234567",ajoittainen,NaN,2025-05-31,NaN,PK,238506.491576,6.709897e+06,2025-06-12,20100.0,853,23,2,NaN,F,F,NaN,NaN,False,notknown,0.0,NaN
2,552.0,POINT (209383.5 6732434.75),579.0,552,Virkistyskohde,rekreationsobjekt,recreational attraction,Veneenlaskupaikka,sjösättningsramp,slipway,Rautilan veneenlaskupaikka,NaN,NaN,Kaislapolku,Vehmaa,Vakka-Suomi,Varsinais-Suomi,"Laiturikiinnitteinen, voi säilyttää isompia veneitä.",NaN,NaN,NaN,NaN,Veneenlaskuun soveltuva luiska,https://www.vehmaa.fi/asuminen-ja-rakentaminen/tekniset-palvelut/venepaikat/,NaN,NaN,+358 (0) 44 7393 721,NaN,Kunta,Vehmaan kunta,NaN,NaN,ajoittainen,NaN,2021-03-10,NaN,Vehmaa,209383.500000,6.732435e+06,2025-06-13,23260.0,918,24,2,NaN,F,F,NaN,NaN,False,notknown,0.0,NaN
3,705.0,POINT (267763 6722867.368079827),732.0,705,Virkistyskohde,rekreationsobjekt,recreational attraction,Rantautumispaikka,landstigningsplats,landing site,Juvan laituri,NaN,NaN,Juvantie 12,Lieto,Turku,Varsinais-Suomi,Laituri Juvan voimalaitoksen yläjuoksulla. Laiturilta voi lähteä melomaan yläjuoksulle päin.\n\n,NaN,NaN,NaN,NaN,NaN,https://www.paimionjoki.fi/luontokohde/liedon-tarvasjoen-luontokohteet,NaN,NaN,NaN,NaN,Yritys,Silver river melontakeskus,NaN,NaN,ei tietoa ylläpitoluokasta,NaN,2020-01-23,NaN,Paimionjokiyhd,267763.000000,6.722867e+06,2025-06-13,21450.0,423,23,2,NaN,F,F,NaN,https://virmafipictures.s3.eu-west-1.amazonaws.com/1648555229740.jpg,False,notknown,0.0,NaN
4,30.0,POINT (239880.64215652 6696265.9289217),54.0,30,Virkistyskohde,Rekreationsobjekt,Recreational attraction,Uimapaikka,Badplats,Unattended beach,Vepon uimapaikka,NaN,NaN,Veponranta 17,Parainen,Turunmaa,Varsinais-Suomi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yritys,NordKalk Oyj,ei ylläpitoa,ei ylläpitoa,ei ylläpitoa,NaN,NaN,NaN,LN,239880.642157,6.696266e+06,2017-04-04,21600.0,573,21,2,NaN,F,F,NaN,NaN,False,notknown,0.0,NaN

In [80]:
pd.set_option('display.max_colwidth', None)
pd.reset_option('display.max_rows')
df.loc[df["equipment"].notna(), ["name_fi", "equipment", "info_fi"]]

,name_fi,equipment,info_fi
1,Turun vierasvenesatama,"septitankin tyhjennys, sähkö, vesi, wifi, jätehuolto, kierrätys, sauna, suihku, pyykkitupa, tankkaus",Venepaikkoja 60 kpl. Ennakkoon varattavia paikkoja on rajoitetusti.
2,Rautilan veneenlaskupaikka,Veneenlaskuun soveltuva luiska,"Laiturikiinnitteinen, voi säilyttää isompia veneitä."
7,Sattmarkin vierassatama,"infotaulu, ravintola, kahvila, tulentekopaikka, vesi, wc, leikkipaikka, liikenneyhteys, luontopolku, uimaranta",Vierasvenepaikkoja 6 kpl. Poiju- ja kylkikiinnitys. Kahvilan laituri on tarkoitettu päiväkävijöille. Yöpymisestä sovittava erikseen.
8,Salmeri,"kahvila, polttoaine, sähkö, vesi, jätehuolto, wc, imutyhjennys, suihku, pesutupa, veneluiska, uimaranta, moottorihuolto","Vierasvenepaikkoja 20 kpl. Poiju-, paalu- ja kylkikiinnitykset. Venetelakka Salmeri."
9,"Pyhäranta, Suojala","ravintola, tulentekopaikka, kauppa, elintarvikekioski, vesi, jätehuolto, wc, suihku, sauna, pesutupa, leikkipaikka, liikenneyhteys, apteekki, veneluiska, uimaranta",Vierasvenepaikkoja 3 kpl. Ankkurikiinnitys.
...,...,...,...
1307,Valpperin hiihtokeskus ja urheilutalo,"Sauna, ulkowc:t, pukeutumistiloja päärakennuksessa","P-paikat urheilutalon ylä- ja alapihalla, Infotaulu reiteistä yläpihan saunan päädyssä. Taloa vuokrataan tapahtumiin."
1308,Vaarniemen laavu ja näkötorni,"laavu, nuotiopaikka, puuvaja",Laavu noin 10 metrin päässä lintutornista
1316,Rautilan rantasauna,"Sauna 30:lle saunojalle, pukuhuoneet, takkatupa, keittiö, wc:t, uimalaituri.","Yleisessä käytössä kesällä arki-iltaisin, muuna aikana vuokrataan yksityiskäyttöön. Ajo Rantapolun kautta. P-paikka 8 autolle."
1317,Himoisten rantasauna,"Sauna, pukuhuoneet, takkatupa, wc:t, tanssilava",Puilla lämpiävä rantasauna HImoisten uimarannan ja venelaitureiden yhteydessä. Saunalla yleisövuoroja sekä vuokrattavia yksityisvuoroja.
1319,Hakkeenpään ranta,"Käymälä, pukukopit, pöytiä ja penkkejä, nuotiopaikka, matonpesupaikka. Runsaasti pysäköintitilaa.","Hakkeenpään uimapaikassa on loiva hiekkaranta. Uimapaikka sijaitsee yhteysaluslaiturin ja kunnan venesataman välissä, uima-alue on eristetty puomeilla. Rannalla ei ole uimalaituria. Nuotiopaikka, runsaasti pysäköintitilaa."

In [81]:
df2 = pd.read_csv("data_to_export_true.csv")

In [82]:
df2.head()

,gid,geom,id,name_fi,name_en,name_se,address,zip,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,accessibil,equipment,www_fi,www_se,www_en,telephone,email,ownerclass,upkeeper,x_eureffin,y_eureffin,timestamp,munici_nro,subreg_nro,region_nro,lipas_type_name,lipas_type_code,lipas_loi_type
0,302,POINT (278939 6765988),302.0,Jättiläisen portaat,NaN,NaN,NaN,32440.0,Loimaa,Loimaa,Varsinais-Suomi,"Jättiläisen portaat, Kanniston Kotieläintilan luontopolun päätepiste.",NaN,NaN,Kohtalaisen helppo luontopolku. Kallion reuna jyrkkä.,NaN,Kunnolliset jalkineet ja sään mukaiset vaatteet.,http://www.kannistontila.fi/metso.html,NaN,NaN,NaN,NaN,Yksityinen,NaN,278939.0,6765988.0,2018-10-04,430,25,2,NaN,NaN,natural-attraction
1,305,POINT (278694 6765746),305.0,Susikivi,NaN,NaN,NaN,32440.0,Loimaa,Loimaa,Varsinais-Suomi,Susikivi on jääkauden aikainen siirtolohkare Kanniston Kotieläintilan luontopolun varrella.,NaN,NaN,Melko helppo.,NaN,Kunnolliset jalkineet ja sään mukainen vaatetus.,http://www.kannistontila.fi/metso.html,NaN,NaN,NaN,NaN,Yksityinen,NaN,278694.0,6765746.0,2018-10-04,430,25,2,NaN,NaN,natural-attraction
2,318,POINT (289408.0000000001 6681497),318.0,Antinmäen pajaluola,NaN,NaN,osoitteeton,25500.0,Salo,Salon seutu,Varsinais-Suomi,"Tarna kertoo, että paikallinen seppä oli pitänyt luolaa aikanaan pajanaan. Antinmäeltä löydetty myös pronssikautinen hautaröykkiö.",NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/antinmaen-pajaluola-salo/,NaN,NaN,NaN,NaN,Yksityinen,ei ylläpitoa,289408.0,6681497.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction
3,326,POINT (283181.0000000001 6695995),326.0,Haukkamäen luola,NaN,NaN,osoitteeton,24130.0,Salo,Salon seutu,Varsinais-Suomi,Näyttävä lippaluola.,NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/luolaloytoja-salossa/,NaN,NaN,NaN,NaN,Kunta,ei ylläpitoa,283181.0,6695995.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction
4,329,POINT (310943.0000000001 6699580),329.0,Hermolanvaha,NaN,NaN,osoitteeton,25410.0,Salo,Salon seutu,Varsinais-Suomi,"Suuri siirtolohkare, joka toiminut Suomusjärven ja Kiikalan kuntien rajakivenä.",NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/hermolanvaha/,NaN,NaN,NaN,NaN,Yksityinen,ei ylläpitoa,310943.0,6699580.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction

In [83]:
df2.shape

(1019, 33)

In [84]:
unique_values = df2["name_fi"].dropna().unique()

print(len(unique_values))

981

In [85]:
duplicates = df2[df2.duplicated(subset=['name_fi', 'x_eureffin', 'y_eureffin'], keep=False)]
len(duplicates)

38

In [86]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df_unique = df2.drop_duplicates(subset=['name_fi', 'x_eureffin', 'y_eureffin'], keep='first')

In [87]:
df_unique.shape

(1000, 33)

In [88]:
bool_info = pd.read_csv("../possible_bool_columns/points_with_boolean_info.csv")

In [89]:
bool_info.head()

,id,gid,name_fi,class2_fi,chall_clas,accessibil,equipment,info_fi,accessibility_prediction,has_toilet
0,NaN,306002,testi20250604uusidb,Luonto- tai lintutorni,NaN,NaN,NaN,testi20250604uusidb,NaN,False
1,974.0,974,Turun vierasvenesatama,Vierassatama,NaN,NaN,"septitankin tyhjennys, sähkö, vesi, wifi, jätehuolto, kierrätys, sauna, suihku, pyykkitupa, tankkaus",Venepaikkoja 60 kpl. Ennakkoon varattavia paikkoja on rajoitetusti.,NaN,False
2,552.0,552,Rautilan veneenlaskupaikka,Veneenlaskupaikka,NaN,NaN,Veneenlaskuun soveltuva luiska,"Laiturikiinnitteinen, voi säilyttää isompia veneitä.",NaN,False
3,705.0,705,Juvan laituri,Rantautumispaikka,NaN,NaN,NaN,Laituri Juvan voimalaitoksen yläjuoksulla. Laiturilta voi lähteä melomaan yläjuoksulle päin.\r\n\r\n,NaN,False
4,30.0,30,Vepon uimapaikka,Uimapaikka,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
data_to_export = df_unique.merge(bool_info[['gid', 'accessibility_prediction', 'has_toilet']], on='gid', how='left')
data_to_export.head()

,gid,geom,id,name_fi,name_en,name_se,address,zip,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,accessibil,equipment,www_fi,www_se,www_en,telephone,email,ownerclass,upkeeper,x_eureffin,y_eureffin,timestamp,munici_nro,subreg_nro,region_nro,lipas_type_name,lipas_type_code,lipas_loi_type,accessibility_prediction,has_toilet
0,302,POINT (278939 6765988),302.0,Jättiläisen portaat,NaN,NaN,NaN,32440.0,Loimaa,Loimaa,Varsinais-Suomi,"Jättiläisen portaat, Kanniston Kotieläintilan luontopolun päätepiste.",NaN,NaN,Kohtalaisen helppo luontopolku. Kallion reuna jyrkkä.,NaN,Kunnolliset jalkineet ja sään mukaiset vaatteet.,http://www.kannistontila.fi/metso.html,NaN,NaN,NaN,NaN,Yksityinen,NaN,278939.0,6765988.0,2018-10-04,430,25,2,NaN,NaN,natural-attraction,NaN,False
1,305,POINT (278694 6765746),305.0,Susikivi,NaN,NaN,NaN,32440.0,Loimaa,Loimaa,Varsinais-Suomi,Susikivi on jääkauden aikainen siirtolohkare Kanniston Kotieläintilan luontopolun varrella.,NaN,NaN,Melko helppo.,NaN,Kunnolliset jalkineet ja sään mukainen vaatetus.,http://www.kannistontila.fi/metso.html,NaN,NaN,NaN,NaN,Yksityinen,NaN,278694.0,6765746.0,2018-10-04,430,25,2,NaN,NaN,natural-attraction,NaN,False
2,318,POINT (289408.0000000001 6681497),318.0,Antinmäen pajaluola,NaN,NaN,osoitteeton,25500.0,Salo,Salon seutu,Varsinais-Suomi,"Tarna kertoo, että paikallinen seppä oli pitänyt luolaa aikanaan pajanaan. Antinmäeltä löydetty myös pronssikautinen hautaröykkiö.",NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/antinmaen-pajaluola-salo/,NaN,NaN,NaN,NaN,Yksityinen,ei ylläpitoa,289408.0,6681497.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction,NaN,False
3,326,POINT (283181.0000000001 6695995),326.0,Haukkamäen luola,NaN,NaN,osoitteeton,24130.0,Salo,Salon seutu,Varsinais-Suomi,Näyttävä lippaluola.,NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/luolaloytoja-salossa/,NaN,NaN,NaN,NaN,Kunta,ei ylläpitoa,283181.0,6695995.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction,NaN,False
4,329,POINT (310943.0000000001 6699580),329.0,Hermolanvaha,NaN,NaN,osoitteeton,25410.0,Salo,Salon seutu,Varsinais-Suomi,"Suuri siirtolohkare, joka toiminut Suomusjärven ja Kiikalan kuntien rajakivenä.",NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/hermolanvaha/,NaN,NaN,NaN,NaN,Yksityinen,ei ylläpitoa,310943.0,6699580.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction,NaN,False

In [91]:
data_to_export.shape

(1000, 35)

In [92]:
'''
import json

data_to_export['properties'] = data_to_export.apply(lambda row: json.dumps({
    'accessibile?': row['accessibility_prediction'],
    'toilet?': row['has_toilet']
}), axis=1)
'''

"\nimport json\n\ndata_to_export['properties'] = data_to_export.apply(lambda row: json.dumps({\n    'accessibile?': row['accessibility_prediction'],\n    'toilet?': row['has_toilet']\n}), axis=1)\n"

In [93]:
data_to_export.head()

,gid,geom,id,name_fi,name_en,name_se,address,zip,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,accessibil,equipment,www_fi,www_se,www_en,telephone,email,ownerclass,upkeeper,x_eureffin,y_eureffin,timestamp,munici_nro,subreg_nro,region_nro,lipas_type_name,lipas_type_code,lipas_loi_type,accessibility_prediction,has_toilet
0,302,POINT (278939 6765988),302.0,Jättiläisen portaat,NaN,NaN,NaN,32440.0,Loimaa,Loimaa,Varsinais-Suomi,"Jättiläisen portaat, Kanniston Kotieläintilan luontopolun päätepiste.",NaN,NaN,Kohtalaisen helppo luontopolku. Kallion reuna jyrkkä.,NaN,Kunnolliset jalkineet ja sään mukaiset vaatteet.,http://www.kannistontila.fi/metso.html,NaN,NaN,NaN,NaN,Yksityinen,NaN,278939.0,6765988.0,2018-10-04,430,25,2,NaN,NaN,natural-attraction,NaN,False
1,305,POINT (278694 6765746),305.0,Susikivi,NaN,NaN,NaN,32440.0,Loimaa,Loimaa,Varsinais-Suomi,Susikivi on jääkauden aikainen siirtolohkare Kanniston Kotieläintilan luontopolun varrella.,NaN,NaN,Melko helppo.,NaN,Kunnolliset jalkineet ja sään mukainen vaatetus.,http://www.kannistontila.fi/metso.html,NaN,NaN,NaN,NaN,Yksityinen,NaN,278694.0,6765746.0,2018-10-04,430,25,2,NaN,NaN,natural-attraction,NaN,False
2,318,POINT (289408.0000000001 6681497),318.0,Antinmäen pajaluola,NaN,NaN,osoitteeton,25500.0,Salo,Salon seutu,Varsinais-Suomi,"Tarna kertoo, että paikallinen seppä oli pitänyt luolaa aikanaan pajanaan. Antinmäeltä löydetty myös pronssikautinen hautaröykkiö.",NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/antinmaen-pajaluola-salo/,NaN,NaN,NaN,NaN,Yksityinen,ei ylläpitoa,289408.0,6681497.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction,NaN,False
3,326,POINT (283181.0000000001 6695995),326.0,Haukkamäen luola,NaN,NaN,osoitteeton,24130.0,Salo,Salon seutu,Varsinais-Suomi,Näyttävä lippaluola.,NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/luolaloytoja-salossa/,NaN,NaN,NaN,NaN,Kunta,ei ylläpitoa,283181.0,6695995.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction,NaN,False
4,329,POINT (310943.0000000001 6699580),329.0,Hermolanvaha,NaN,NaN,osoitteeton,25410.0,Salo,Salon seutu,Varsinais-Suomi,"Suuri siirtolohkare, joka toiminut Suomusjärven ja Kiikalan kuntien rajakivenä.",NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/hermolanvaha/,NaN,NaN,NaN,NaN,Yksityinen,ei ylläpitoa,310943.0,6699580.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction,NaN,False

In [94]:
#data_to_export = data_to_export.drop(columns=["gid", "accessibility_prediction", "has_toilet"])
data_to_export.shape

(1000, 35)

In [126]:
TYPE_PROPERTIES = {
"Kalastuskohde piste" : {
    "bool": ["toilet", "pier"]
},
"Uimaranta" : {
    "bool": ["toilet", "sauna", "pier", "changing-rooms", "shower"]
}, 
"Uimapaikka" : {
    "bool": ["toilet", "sauna", "pier", "changing-rooms", "shower"]
},
"Laavu, kota tai kammi" : {
    "bool": ["toilet"]
}, 
"Tupa" : {
    "bool": ["toilet"]
}, 
"Telttailu ja leiriytyminen" : {
    "bool": ["toilet"]
}, 
"Luontotorni": {
    "bool": ["toilet"]
    },
"Tulen/ruuanlaittopaikka": {
    "bool": ["toilet"]
    },

"opastuspiste": {
    "bool": ["toilet", "parkkipaikka"]
},
"Talviuimapaikka" : {
    "bool": ["toilet", "sauna", "pier", "changing-rooms", "shower", "ice-reduction"]
},
"Koiraurheilualue": {
    "bool": ["toilet", "ligthing"]
},
"Kaukalo": {
    "bool": ["toilet", "ligthing", "changing-rooms"]
},
"Ulkoilumaja/hiihtomaja": {
    "bool": ["toilet"]
},
"Veneilyn palvelupaikka": {
    "bool": ["toilet", "pier", "boat-launching-spot"]
},
}

In [127]:
KEYWORDS = {
    "laituri": ["laituri", "pier"],
    "sauna": ["sauna"],
    "pukukopit": ["pukuhuone", "changing room", "pukukopit"],
    "suihku": ["suihku", "shower"],
    "yleisowc": ["wc", "kuivakäymälä", "käymälä", "huussi", "puucee", "vessa", "inva-wc", "yleisöwc"],
    "jäätymisenesto": ["jäätymisenesto"],
    "veneen laskupaikka": ["veneenlaskupaikka"]
}

In [128]:

import json

def extract_properties(row):
    # Combine equipment, info_fi, and accessibility text
    text = f"{row.get('equipment', '')} {row.get('info_fi', '')} {row.get('accessibil', '')}".lower()
    props = {}

    # Only look up type properties if lipas_type_name is not null
    if pd.notna(row.get('lipas_type_name')):
        type_config = TYPE_PROPERTIES.get(row['lipas_type_name'], {})

        # Booleans
        for prop in type_config.get("bool", []):
            keywords = KEYWORDS.get(prop, [])
            props[prop + "?"] = any(k in text for k in keywords)

        # Categorical
        for prop, values in type_config.get("categorical", {}).items():
            for val in values:
                if val in text:
                    props[prop] = val
                    break

    # Always add accessibility info if available
    if pd.notna(row.get('accessibil')):
        props["accessible?"] = row['accessibility_prediction']  # assuming it's True/False

    # Convert to JSON string for direct export
    return json.dumps(props)

In [129]:
import pandas as pd

# Apply the function to each row and store the results in a new column
data_to_export['properties'] = data_to_export.apply(extract_properties, axis=1)

# Check the result
data_to_export.shape

(1000, 36)

In [131]:
data_to_export = data_to_export.drop(columns=["gid", "accessibility_prediction", "has_toilet"])
data_to_export.shape

(1000, 33)

In [ ]:
data_to_export = data_to_export.drop(columns=["gid", "accessibility_prediction", "has_toilet"])
data_to_export.head()

,geom,id,name_fi,name_en,name_se,address,zip,municipali,subregion,region,info_fi,info_se,info_en,chall_clas,accessibil,equipment,www_fi,www_se,www_en,telephone,email,ownerclass,upkeeper,x_eureffin,y_eureffin,timestamp,munici_nro,subreg_nro,region_nro,lipas_type_name,lipas_type_code,lipas_loi_type,properties
0,POINT (278939 6765988),302.0,Jättiläisen portaat,NaN,NaN,NaN,32440.0,Loimaa,Loimaa,Varsinais-Suomi,"Jättiläisen portaat, Kanniston Kotieläintilan luontopolun päätepiste.",NaN,NaN,Kohtalaisen helppo luontopolku. Kallion reuna jyrkkä.,NaN,Kunnolliset jalkineet ja sään mukaiset vaatteet.,http://www.kannistontila.fi/metso.html,NaN,NaN,NaN,NaN,Yksityinen,NaN,278939.0,6765988.0,2018-10-04,430,25,2,NaN,NaN,natural-attraction,{}
1,POINT (278694 6765746),305.0,Susikivi,NaN,NaN,NaN,32440.0,Loimaa,Loimaa,Varsinais-Suomi,Susikivi on jääkauden aikainen siirtolohkare Kanniston Kotieläintilan luontopolun varrella.,NaN,NaN,Melko helppo.,NaN,Kunnolliset jalkineet ja sään mukainen vaatetus.,http://www.kannistontila.fi/metso.html,NaN,NaN,NaN,NaN,Yksityinen,NaN,278694.0,6765746.0,2018-10-04,430,25,2,NaN,NaN,natural-attraction,{}
2,POINT (289408.0000000001 6681497),318.0,Antinmäen pajaluola,NaN,NaN,osoitteeton,25500.0,Salo,Salon seutu,Varsinais-Suomi,"Tarna kertoo, että paikallinen seppä oli pitänyt luolaa aikanaan pajanaan. Antinmäeltä löydetty myös pronssikautinen hautaröykkiö.",NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/antinmaen-pajaluola-salo/,NaN,NaN,NaN,NaN,Yksityinen,ei ylläpitoa,289408.0,6681497.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction,{}
3,POINT (283181.0000000001 6695995),326.0,Haukkamäen luola,NaN,NaN,osoitteeton,24130.0,Salo,Salon seutu,Varsinais-Suomi,Näyttävä lippaluola.,NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/luolaloytoja-salossa/,NaN,NaN,NaN,NaN,Kunta,ei ylläpitoa,283181.0,6695995.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction,{}
4,POINT (310943.0000000001 6699580),329.0,Hermolanvaha,NaN,NaN,osoitteeton,25410.0,Salo,Salon seutu,Varsinais-Suomi,"Suuri siirtolohkare, joka toiminut Suomusjärven ja Kiikalan kuntien rajakivenä.",NaN,NaN,NaN,NaN,NaN,http://retkipaikka.fi/vapaa/hermolanvaha/,NaN,NaN,NaN,NaN,Yksityinen,ei ylläpitoa,310943.0,6699580.0,2017-11-13,734,22,2,NaN,NaN,natural-attraction,{}

In [134]:
data_to_export = data_to_export.drop(columns=["upkeeper", "chall_clas"])
data_to_export.shape

(1000, 31)

In [137]:
data_to_export["id"] = data_to_export["id"].astype("Int64")
data_to_export["zip"] = data_to_export["zip"].astype("Int64")
data_to_export["lipas_type_code"] = data_to_export["zip"].astype("Int64")
data_to_export.dtypes

geom                object
id                   Int64
name_fi             object
name_en             object
name_se             object
address             object
zip                  Int64
municipali          object
subregion           object
region              object
info_fi             object
info_se             object
info_en             object
accessibil          object
equipment           object
www_fi              object
www_se              object
www_en              object
telephone           object
email               object
ownerclass          object
x_eureffin         float64
y_eureffin         float64
timestamp           object
munici_nro           int64
subreg_nro           int64
region_nro           int64
lipas_type_name     object
lipas_type_code      Int64
lipas_loi_type      object
properties          object
dtype: object

In [139]:
data_to_export.to_csv("virma_lipas_export.csv", index=False)